### ISSUE TITLE
[Bug] MiniScaled/ImmersivePortal interaction

### ISSUE THREAD

**Issue by Nitjsefnie** [tr7zw/EntityCulling#103]
Portal entity is not fully rendered even though on screen
![2023-03-14_13 28 20](https://user-images.githubusercontent.com/75166987/225002800-bf0178c7-0a6e-4b51-b0fe-2bb26d14bb88.png)

Without EntityCulling
![2023-03-14_13 35 27](https://user-images.githubusercontent.com/75166987/225002905-c56b5146-5cae-4192-a6c6-3267aaa84bb0.png)

Using Minecraft 1.19.3, Fabric Loader 0.14.17, Fabric API 0.75.1, EntityCulling 1.6.1, ImmersivePortals 2.5.1 and MiniScaled 2.1.1

**Comment by tr7zw** [comment]
That doesn't look like anything related to this mod? Either it renders, or it doesn't. On the top image your camera is just clipping into the floor?

**Comment by Nitjsefnie** [comment]
It's not clear in the screenshots, a video would be better but I don't have the capabilities to make one, but if you accept my discord request, I could show you on stream

**Comment by tr7zw** [comment]
I'm at work. My point is, this has most likely nothing to do with this mod. You can try binding the debug key in the controls that turn the mod on/off. If standing perfectly still and pressing that key makes the issue appear/vanish, then it's this mod. Otherwise it's most likely the near clipping plane intersecting with the floor due to the player size.

**Comment by Nitjsefnie** [comment]
Very weird, the bug persisted after 3-4 mod swaps but now it's just gone, apparently there's no bug anymore? ^^

**Comment by tr7zw** [comment]
I'd suggest making the player a tiny bit bigger. MC isn't designed for the camera to be this close to things, and the camera clipping into walls/floors will result in exactly that behaviour.

**Comment by Nitjsefnie** [comment]
First of all, I'm not the developer. Second, the player is actually full size, just in a pocket dimension with really huge Portal entities around which you can use to exit, rendering the surrounding

**Comment by Nitjsefnie** [comment]
Accidental reopen missclick...
