### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by andreasdc** [tr7zw/EntityCulling#105]
Could it be optimized a little by any chance?
![image](https://user-images.githubusercontent.com/82218780/230734981-58295505-855e-4984-a2bb-13717d5c95e0.png)

**Comment by tr7zw** [comment]
It's sleeping 74% of the time?

**Comment by tr7zw** [comment]
This is already pretty optimized. If you have any insight into further optimizing it, be my guest. But you probably didn't notice that this is also its own thread(entirely unlinked to the game), and is only active 26% of the time. Even at 100%, it wouldn't have an impact on the framerate(assuming your PC has one free CPU core).
