### ISSUE TITLE
'minecraft:boat' always render

### ISSUE THREAD

**Issue by FazziCLAY** [tr7zw/EntityCulling#106]
there are three screenshots here. The first two are made with F3+A clamped, the last one without. The first one with the mod disabled, and the second one with the enabled one. As you can see the boats are always rendered

![2023-04-12_15 36 44](https://user-images.githubusercontent.com/68351787/231459329-05e2ea1d-6ba3-426f-9d6c-eb446dff9e25.png)
![2023-04-12_15 36 48](https://user-images.githubusercontent.com/68351787/231459345-1d495dfc-6fd2-4614-b96b-4a0324547f55.png)
![2023-04-12_15 36 51](https://user-images.githubusercontent.com/68351787/231459352-1841a1f4-dc11-4083-a277-62268def643b.png)

**Comment by tr7zw** [comment]
I think I put boats and minecarts on an exclude(maybe under certain conditions). This shouldn't be an issue.

**Comment by FazziCLAY** [comment]
on servers, boats are actively used for movement in nether. I think the choice of behavior can at least be added to the mod config

**Comment by tr7zw** [comment]
This was done to prevent bugs, so no config value.

**Comment by tr7zw** [comment]
Looking at it again, boats are part of the config for tick culling. For rendering they don't have anything special(anymore?).

**Comment by tr7zw** [comment]
Welp, turns out, there was a massive bug in the code with the tick culling, adding it into the normal whitelist. Boats will now be culled correctly, and just be allowed to tick, as intended.
