### ISSUE TITLE
Entities outside of screen

### ISSUE THREAD

**Issue by andreasdc** [tr7zw/EntityCulling#109]
What happens when entities are outside of the screen? I see they are still rendered, right?

**Comment by tr7zw** [comment]
Minecraft does a view frustum cull. So anything outside the screen gets skipped already.

**Comment by andreasdc** [comment]
Are you sure? On f3 it shows that they are rendered.

**Comment by tr7zw** [comment]
This mod doesn't touch the f3 numbers. Also, an easy way to check it: put a thousand mobs into a pen. Look at it, then look away. Even in vanilla, this works.

**Comment by andreasdc** [comment]
![image](https://user-images.githubusercontent.com/82218780/234665118-926d634c-c287-4c37-be0c-43162e7a02ca.png)

**Comment by tr7zw** [comment]
These numbers are incorrect in combination with other mods like iris or optifine, and are only meant to indicate that stuff is working correctly and the expected ratios. Like I said, just test it. Alternatively: bind the debug hotkey to toggle culling on/off on the fly, so check the fps difference.

**Comment by andreasdc** [comment]
Ok, I'm back after some testing. Entities outside of the screen still lag. When you have entities behind a wall with entity culling I had around 150 fps, without I had around 60. Without the entities the fps are way higher.

**Comment by tr7zw** [comment]
As I said, the screen is entirely unused by this mod. Vanilla Mc skips the rendering of entities behind you. This mod does some optimizations like not updating the animations of things that didn't render. But of, having a ton of entities is still more stuff to calculate, so it will have some inpact on the fps. Just less with this mod.

**Comment by andreasdc** [comment]
Yes, but it still takes fps even when entities are outside of the screen/behind a wall.

**Comment by tr7zw** [comment]
And? They still need to update, move, network packets, Mc needs to check rather they are I'm the screen space, this mod needs to check rather they have become visible. Still lots of calculations, and if your cpu is not that fast, you will still feel that with enough entities.

**Comment by andreasdc** [comment]
There for sure is a way to optimize it, you don't need 1k entities to feel the lag, with 100 you already have fps drop.

**Comment by tr7zw** [comment]
I can just repeat myself: Vanilla already does a good job, and EntityCulling cuts out as much as possible.
If 100 entities outside your view lag your game, that sounds like you are playing on hardware that is just too old/slow. I don't know what you want to hear from me^^
