### ISSUE TITLE
Problem with EntityCulling and Tweakeroo FreeCam

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [tr7zw/EntityCulling#11]
Similar to #1 but NOT a duplicate. Here is a video (works fine in spectator, but breaks in tweakeroo freecam):

https://gph.is/g/aNx87r1

**Comment by DragonEggBedrockBreaking** [comment]
Issue only seems to exist when the player's head is inside a block. I will try reproducing in survival + creative by pushing blocks into the player's head, to confirm my suspicion.

**Comment by DragonEggBedrockBreaking** [comment]
That's strange, if my head is inside a block in creative or survival, then it is fine and works properly, but the moment I enter freecam, it starts glitching like in the video I posted above.

**Comment by tr7zw** [comment]
I mean that is basically the issue. Head is in a wall = you can't see anything. Tweakeroo just removes the block overlay, causing you to see that you can't see stuff^^

**Comment by DragonEggBedrockBreaking** [comment]
> I mean that is basically the issue. Head is in a wall = you can't see anything. Tweakeroo just removes the block overlay, causing you to see that you can't see stuff^^

So is it possible to add tweakeroo freecam to the spectator fix commit?

**Comment by tr7zw** [comment]
Not without adding dependencies to tweakeroo. I guess the real issue is that it's technically a hack like xray that is kinda hard to make work as you'd expect. (And yes xray will be broken too). Maybe redoing the logic to allow rays to go through walls when the initial position is also in a wall till it's outside the wall once could work. But this is understandably kinda low prio since it only impacts basically hacks and not vanilla gameplay.

**Comment by DragonEggBedrockBreaking** [comment]
> But this is understandably kinda low prio

Yea, makes sense, and it is kinda rare for me to have big entities around while being in freecam and inside a block, especially since, I use freecam to view builds, and do not use it for xray or for cheating on servers.

> Maybe redoing the logic to allow rays to go through walls when the initial position is also in a wall till it's outside the wall once could work.

I understood none of that, but if it potentially works, then it potentially works...

> since it only impacts basically hacks and not vanilla gameplay.

I would argue that there are non-hacky ways of using freecam, but then again, supporting other low-priority mods, especially features that are mostly used in hacky ways (because it is more likely for someone to be using an actual cheat client for freecam and/or xray, rather than using a utility mod to view their builds better.


So should I keep this open? I suggest keeping it open, but adding a new `low priority` tag, so that people don't see this and ask why you haven't fixed it yet (without reading the conversation).

**Comment by Nicolas-GE** [comment]
i think having a special rule if the camera is in a wall to just disable culling is a good idea, but i think this should be set as low priority too

**Comment by CuteistCat** [comment]
i think a way of making this is it ignores blocks with transparent pixels

**Comment by tr7zw** [comment]
This should be fixed for some time now since the spectator mode changes.
