### ISSUE TITLE
[Enhancement] Split tracingDistance to EntityTracingDistance and BlockEntityTracingDistance

### ISSUE THREAD

**Issue by HowardZHY** [tr7zw/EntityCulling#110]

**Comment by tr7zw** [comment]
Why?

**Comment by tr7zw** [comment]
Making the tracking distance larger is not really possible due to the cubic square law, so the only option would be to make it smaller. And why try to track one smaller than the other? What would be the benefit?

**Comment by HowardZHY** [comment]
On some shooting server the view distance is 256 to sniper players & mobs but the map is complex.

**Comment by tr7zw** [comment]
Again, setting it to 256 will just break it and not making it work at all.

**Comment by HowardZHY** [comment]
the ideal settings might be
BlockEntityTracingDistance 32
EntityTracingDistance 240

**Comment by tr7zw** [comment]
No. Anything above the default setting will cause issues. The issue is not for how many it's culling, but the maximum range.

**Comment by tr7zw** [comment]
At 240 range, it will create a 3.4gb cache that needs to be reset 20 times per second in theory. Thats just a no go.
