### ISSUE TITLE
Not letting me play in 1.8.8

### ISSUE THREAD

**Issue by BlueCorallite** [tr7zw/EntityCulling#113]
I don't know if you still support older versions, but I'll ask anyway
I'm trying to run version 1.5.0 of EntityCulling in 1.8.8. I'm using 1.8.8 because I'm playing a map that specifically requires that version. however, Forge won't let me run it because it wants me on 1.8.9. Anyway I can fix this?

![image](https://github.com/tr7zw/EntityCulling/assets/64111918/a9d072e4-c99d-40c0-a452-37bfc7872b56)
This is the one I downloaded and it does support 1.8.8 according the Modrinth page.

**Comment by tr7zw** [comment]
Uhhh what does it say? Potentially I messed up the metadata.

**Comment by BlueCorallite** [comment]
![image](https://github.com/tr7zw/EntityCulling/assets/64111918/66d911a3-4d68-4afd-abf0-94fedee53157)

**Comment by tr7zw** [comment]
Uhhh you could try to set it to work with 1.8.8 in the toml inside the jar. If that doesn't work, then it's just not compatible at all with 1.8.8.

**Comment by BlueCorallite** [comment]
All right, how can I do that?

**Comment by tr7zw** [comment]
Actually, just looked into the jar, and it says 1.17.1. So apparently in 1.8 this was still done differently, no easy way to work around that. It's also compiled against 1.8.9, not 1.8.8. I'll remove the 1.8.8 tag from curseforge, on Modrinth I never uploaded it.

**Comment by BlueCorallite** [comment]
Okay no problem, thanks for your help
