### ISSUE TITLE
1.20.1 support

### ISSUE THREAD

**Issue by SLinxTheFox** [tr7zw/EntityCulling#114]
Most 1.20 mods work in 1.20.1, but it would be nice to be sure.

though 1.20.1 touches something with chunk rendering that can apparently affect entities, what the dev said was a bit over my head, so i'm not sure how much that would affect this mod if at all

**Comment by tr7zw** [comment]
The mod is already marked as 1.20.1 compatible, at least on modrinth.

**Comment by SLinxTheFox** [comment]
oh alright, i'll try it then, thanks

**Comment by SLinxTheFox** [comment]
seems to be working, though i should have tested with just sodium. thank you!

**Comment by tr7zw** [comment]
I'll go through the curse files later today to fix the markings.
