### ISSUE TITLE
Incompatibility with GeckoLib (?)

### ISSUE THREAD

**Issue by GitUser14975** [tr7zw/EntityCulling#115]
The game keeps crashing and the Not Enough Crashes mod says that the suspected mods for causing the crash are EntityCulling and GeckoLib. Someone with the same issue reported it to GeckoLib, but they said that it looks like an issue with EntityCulling.
https://crashy.net/f0642420-a98d-4476-9501-d43e47f69ba4

**Comment by tr7zw** [comment]
Doesn't look related to this mod. It's something about the shadow rendering/gecko lib trying to replace the renderer, while the entity is null. Best-case ask over at GeckoLib.
