### ISSUE TITLE
Entity culling no working in Create mod

### ISSUE THREAD

**Issue by GitJhopa** [tr7zw/EntityCulling#117]
![image](https://github.com/tr7zw/EntityCulling/assets/86250668/7cfc70e4-b7c4-4f6c-9142-aa0130a82755)
see screenshot, no culling blocks. my fps low.

**Comment by tr7zw** [comment]
They are excluded to prevent visual bugs. Also that looks like more than 64 blocks away, where normal block entities are not rendered by vanilla and this mod stops checking. Might be that Create switched to using flywheel more, bypassing all the culling logic entirely too. Not a bug.

**Comment by GitJhopa** [comment]
My FPS is suffering

**Comment by tr7zw** [comment]
Try removing the blacklist lines from the config file, but that might not work in case it's using flywheel. Either ask on Creates end if something was done in regards of performance, or you might need to upgrade your rig if a few blocks impact the performance hard.

**Comment by GitJhopa** [comment]
Already deleted. Doesn't work (((Please help, FPS suffers a lot from dungeons and when there are a lot of players and a lot of mechanisms. I would like to disable their display if they are further than a certain number of blocks.

**Comment by tr7zw** [comment]
Again, ask at creates end maybe for a performance mode or something.

**Comment by GitJhopa** [comment]
Forge + Rubidium + Rubidium Extra + EntityCulling = 1000-1200 FPS
Forge + Rubidium + Rubidium Extra + EntityCulling + XaerosMinimap = 800-950 FPS
Forge + Rubidium + Rubidium Extra + EntityCulling + XaerosMinimap+Create+IDAS = 250-400 FPS

As you can see FPS dropped by almost 4-5 times

**Comment by tr7zw** [comment]
And why are you asking me there^^? Clearly not this mods fault that performance degrades. Also, 250+ fps is not an issue?

**Comment by GitJhopa** [comment]
> And why are you asking me there^^? Clearly not this mods fault that performance degrades. Also, 250+ fps is not an issue?

Problem, need 600+

**Comment by elenawinters** [comment]
Then remove your minimap or create or IDAS.

Minimaps tend to drop performance quite a bit. It is to be expected that a drop will happen with them.

**Comment by GitJhopa** [comment]
Already did, as a result reduces Create mod more.
