### ISSUE TITLE
Config file deletes itself upon game reload

### ISSUE THREAD

**Issue by Euphorian777** [tr7zw/EntityCulling#122]
Whenever I reload the game, Entity Culling's config file is deleted and then remade with the default settings; rendering my previous changes to the config null.

**Comment by tr7zw** [comment]
The config file deletes itself when it's invalid. Other than the whitelist, nothing should be touched in there. And for the whitelist ensure that you have a ``,`` between entries, but not after the last one, also not forgetting a ``"`` somewhere.
