### ISSUE TITLE
Issue players are invisible

### ISSUE THREAD

**Issue by JAVIxcr** [tr7zw/EntityCulling#123]
I have a server called Puchacraft.
This has the version 1.16.5-forge-36.2.34

The issue happens when players teleports to a new location near to me, or usually when they come from the back of my camera.
They are completely invisible and I am only able to see them when they sit in a chair.

This happens with other entities, for example the mod: camera-1.16.5-1.0.14

Thank you for all your efforts.

If you need I can give you videos or pictures, just comment.

**Comment by tr7zw** [comment]
I mean, the camera is entirely unused and teleporting is not handled any different then normal walking. Try binding the debug key and check if that makes them visible again, but from the description it doesn't sound like this mod.

**Comment by tr7zw** [comment]
Closing as inactive.
