### ISSUE TITLE
Possible incompatible mod 1.12.2

### ISSUE THREAD

**Issue by ChromaPIE** [tr7zw/EntityCulling#124]
EntityCulling crashes with [Smooth Entity Light](https://www.curseforge.com/minecraft/mc-mods/smooth-entity-light), caused by it loading `net.minecraft.entity.Entity` too early
Log can be found here: https://github.com/LakMoore/Smooth-Entity-Light/issues/22

After checking similar problems internet-wide, and more mods start to crash bc of the same issue after I removed EntityCulling from my instance for a further test, I guess it's not something that can be fixed here, and for the fact that I'm not likely to get a fix from their side, it's just a request to add that mod to incompatible mods list.

**Comment by tr7zw** [comment]
Wrong mod, there is no 1.12.2 version of this mod.

**Comment by ChromaPIE** [comment]
omfg im so sorry for the inconvenience
