### ISSUE TITLE
Entities incorrectly culled at certain third person perspectives

### ISSUE THREAD

**Issue by SPINZ1** [tr7zw/EntityCulling#126]
When the player is positioned in front of blocks, entities are culled at certain third person camera angles despite being otherwise visible on screen

1.20.1 Fabric 
All mods:
![image](https://github.com/tr7zw/EntityCulling/assets/145732023/fbe4e6ae-e10f-45c6-9869-cfe95c309bdb)
https://github.com/tr7zw/EntityCulling/assets/145732023/b3cd7c1e-dd4c-4684-acdb-5c35e00b1cf4

**Comment by tr7zw** [comment]
Nothing I can do without an example.

**Comment by tr7zw** [comment]
Also, perhaps a duplicate of [this](https://github.com/tr7zw/EntityCulling/issues/39#issuecomment-1035777864) (is the camera hitting a wall/ceiling)?

**Comment by SPINZ1** [comment]
Yes

**Comment by SPINZ1** [comment]
https://github.com/tr7zw/EntityCulling/assets/145732023/b3cd7c1e-dd4c-4684-acdb-5c35e00b1cf4

**Comment by Julienraptor01** [comment]
I've got an exact setup where i reproduced the issue
1. Create a world with seed `-5397288099815253827`
2. Do `/tp @s -101.5 69.0 -37.5 0.0 0.0`
3. Press F5 twice

you should get this result https://youtu.be/dVzwpJ4Ezao

**Comment by tr7zw** [comment]
Yea I noticed that too recently on the latest version. From what I can tell the F5 camera slightly clips into the block, causing this behavior. I will fix that next update by probably making rays starting inside blocks being allowed to pass blocks till it's out once. It should also fix spectator mode hopefully.

**Comment by tr7zw** [comment]
Fixed in 1.6.4
