### ISSUE TITLE
[Suggestion] Option to cull display entities

### ISSUE THREAD

**Issue by Taiyou06** [tr7zw/EntityCulling#129]
I know whole gist of display entities are rendering stuff without weird screen culling issues, but an option could be added to config file.

EDIT: Additionally a `force-render` distance would be great to eliminate close up culling issues.

**Comment by tr7zw** [comment]
I don't understand, what is the issue with display entities? They should already be culled by the mod, at worst they have some issues with odd transformations and too large models(same issue as with armorstands), when the bounding box doesn't line up with the rendered object.
And why would a minimum render distance be helpful, can you give an example where it would change anything?

**Comment by Taiyou06** [comment]
> I don't understand, what is the issue with display entities? They should already be culled by the mod

When i was checking with debug mode on they weren't so i thought they are not being culled. If it's bounding box related then yeah that would explain.

> And why would a minimum render distance be helpful, can you give an example where it would change anything?

Some servers use display entities for rideable stuff so force-render type distance config would eliminate those false culling issues.

**Comment by tr7zw** [comment]
Closing this issue as invalid. Display Entities work like all other entities, only that they can have custom culling values. So if they don't cull correctly, that's an issue with the map/server and also affects vanilla.
