### ISSUE TITLE
Entities not rendered when in sight.

### ISSUE THREAD

**Issue by Xrey274** [tr7zw/EntityCulling#13]
Example with lead:
https://imgur.com/a/f68F1eK

**Comment by tr7zw** [comment]
There is a way bigger issue that has been fixed for the next release. Should ™️ be done later today.

**Comment by Xrey274** [comment]
Requesting for the issue to be opened again. Building with the latest commit on external branch makes the problem harder to replicate, but it's still there. I will post a video later.

**Comment by tr7zw** [comment]
Update: this isn't an issue of the culling mod that the player turns invisible when too high/low. You can test that by toggling the culling off with the hotkey, the player stays invisible. Also, it doesn't happen with just the culling mod installed. My guess is that it's optifine?

**Comment by tr7zw** [comment]
Sry comment was from the wrong ticket. Can you send me a setup to replicate this on the external branch(World file via discord/github upload or so)?

**Comment by Xrey274** [comment]
Yeah sure, what's your discord handle?
