### ISSUE TITLE
Sodium useEntityCulling

### ISSUE THREAD

**Issue by andreasdc** [tr7zw/EntityCulling#132]
Does this option makes EntityCulling unnecessary?
https://github.com/CaffeineMC/sodium-fabric/blob/ac3bc61fb0c8f5f7092cbcc03b395b853cce213e/src/main/java/me/jellysquid/mods/sodium/client/render/SodiumWorldRenderer.java#L381C9-L381C9

**Comment by tr7zw** [comment]
As stated on the mod page, no.

**Comment by andreasdc** [comment]
> As stated on the mod page, no.

"If enabled, entities determined not to be in any visible chunks will be skipped during rendering. This can help improve performance by avoiding the rendering of entities located underground or behind walls."
So the Sodium's check should check for walls too.

**Comment by tr7zw** [comment]
Again: Sodium does it on a CHUNK basis. So if the entire subchunk is not visible(for example underground caves), there is no reason to render mobs in there. EntityCulling works based on the actual blocks, so entities inside a house or basement are not rendered while not inside.
These just share the name, they work entirely differently and have other purposes(Sodium has it as a byproduct when determining which subchunks to render in the first place).

**Comment by andreasdc** [comment]
So if you are on the same chunk and there are entities under ground you still see them?

**Comment by tr7zw** [comment]
Just... leave sodium's option turned on and that's it.

**Comment by andreasdc** [comment]
> Just... leave sodium's option turned on and that's it.

Ok, but I'm asking if the EntityCulling is needed and does it improve performance with Sodium's option.

**Comment by tr7zw** [comment]
Again again: Sodiums option has nothing to do with this mod. It doesn't do the same thing, one doesn't replace the other. It was developed with Sodium and all benchmarks and numbers are taken with Sodium. Yes, the entire point of the mod is to run with Sodium.
