### ISSUE TITLE
[BUG] Fabric version depend on Fabric API but doesn't declare it in FMJ

### ISSUE THREAD

**Issue by Julienraptor01** [tr7zw/EntityCulling#133]
I was testing things for another bug and narrowed it down to potentially be caused by EntityCulling
so i tried to remove all mods but it since it doesn't have any dependencies and launch the game
however this did produce a [crashlog](https://github.com/tr7zw/EntityCulling/files/13879098/crash-2024-01-09_22.08.05-client.txt)
by reading lines 25 and 31, you can easily see that the mod tries to call some code from the fabric API, but doesn't succeed
```log
25: Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/event/lifecycle/v1/ClientTickEvents
31: Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents
```
this is due to the code right here https://github.com/tr7zw/EntityCulling/blob/987fdb1dac616d180e4a2c93b1e89b15e003bf3a/EntityCulling-Fabric/src/main/java/dev/tr7zw/entityculling/EntityCullingMod.java#L19-L24

**Comment by tr7zw** [comment]
Hm true, will fix that next release. I keep forgetting that, as the CurseForge launcher installs the Fabric API by default anyway.

**Comment by Julienraptor01** [comment]
> Hm true, will fix that next release. I keep forgetting that, as the CurseForge launcher installs the Fabric API by default anyway.

OOF truly a CursedForge moment

**Comment by tr7zw** [comment]
Without them, none of my mods would be a thing... sooo^^
But yea, starting fabric without the API is usually never correct.

**Comment by tr7zw** [comment]
God, this issue caused so many issues.

**Comment by tr7zw** [comment]
Closing as this has been fixed. But jeez this caused soooo many follow up issues.
