### ISSUE TITLE
[Suggestion] Render only glow effect if entity.isCulled

### ISSUE THREAD

**Issue by EternalHuman** [tr7zw/EntityCulling#134]
Drow only glow effect if entity.isCulled.

![image](https://github.com/tr7zw/EntityCulling/assets/71584363/f6a24c1f-e8c5-4d71-bb64-03a78b6ede4a)

**Comment by tr7zw** [comment]
I have no clue what you mean by that.

**Comment by EternalHuman** [comment]
This will increase fps due to disabling the rendering of useless parts (Hand item texture/model, armor).

**Comment by tr7zw** [comment]
The outline requires rendering the player. I don't think there is a point in trying to "minimize" the amount of things used to render the outline, as this happens relatively rarely, and would just look like a bug when the outline changes(and the performance gain would be next to none).
