### ISSUE TITLE
[BUG?] Invisible players issue

### ISSUE THREAD

**Issue by EternalHuman** [tr7zw/EntityCulling#135]
https://youtu.be/kWeFX8JKHZ4

**Comment by tr7zw** [comment]
Try to replicate that without other mods and in a LAN world, not on a random server.

**Comment by EternalHuman** [comment]
> Try to replicate that without other mods and in a LAN world, not on a random server.

![image](https://github.com/tr7zw/EntityCulling/assets/71584363/a7a5e642-ae17-4f8b-9f89-9b07e43fe7ca)
Only EntityCulling

**Comment by tr7zw** [comment]
![grafik](https://github.com/tr7zw/EntityCulling/assets/5133936/966379e2-d9c3-4bf5-90dc-29e0665e8115)
![grafik](https://github.com/tr7zw/EntityCulling/assets/5133936/a95693c9-dfd8-4b02-8fba-c960c7d58096)


>Try to replicate that without other mods and in a LAN world, not on a random server.

**Comment by EternalHuman** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/5133936/305253541-966379e2-d9c3-4bf5-90dc-29e0665e8115.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMzk5NjcsIm5iZiI6MTcwODAzOTY2NywicGF0aCI6Ii81MTMzOTM2LzMwNTI1MzU0MS05NjYzNzllMi1kOWMzLTRiZjUtOTBkYy0yOWUwNjY1ZTgxMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTVUMjMyNzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWYwN2VkOThlYTA3OTFkNjBhM2VmMjE5ZWJiYWVkNDFlYTZlYTQ0NzRjNGRjMWFhM2M0Yjg4MzMwYzE5ZjlkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uLfEZDbPimODXhMnzSfVU5rpyVyw5A7kK8EYBlJdvXQ) ![grafik](https://private-user-images.githubusercontent.com/5133936/305253634-a95693c9-dfd8-4b02-8fba-c960c7d58096.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMzk5NjcsIm5iZiI6MTcwODAzOTY2NywicGF0aCI6Ii81MTMzOTM2LzMwNTI1MzYzNC1hOTU2OTNjOS1kZmQ4LTRiMDItOGZiYS1jOTYwYzdkNTgwOTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTVUMjMyNzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjBjMGExNTI2ZTJjOTQ3MGVmODM4MGUzOTNmYjA2MjkyNGRmODNjOTJkOGY2ZTFjYmE1MDRkOTU5MWRiNGVhNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oHAYCeysl8wWVmeezcnzFaKz6zjHXJ4WfWV6jjyZlNo)
> 
> > Try to replicate that without other mods and in a LAN world, not on a random server.

This is pure Paper server with only important plugins.

**Comment by tr7zw** [comment]
It's still a heavily modified client and server. If players just stayed invisible that would have been noticed long ago with millions of downloads of 1.16.5 forge.

**Comment by EternalHuman** [comment]
Here's the only way to fix it
"tickCulling": false in config

**Comment by tr7zw** [comment]
Just looked it up, you are running a hackclient, so a) not vanilla and b) unsupported. I won't add workarounds for badly coded hackclients.
![grafik](https://github.com/tr7zw/EntityCulling/assets/5133936/db06238c-e95d-450e-a9cd-6ced0b5002b3)

**Comment by EternalHuman** [comment]
![image](https://github.com/tr7zw/EntityCulling/assets/71584363/d26f8375-7add-4c35-874f-e4b942fb97a5)

Pure LAN server
