### ISSUE TITLE
[BUG] Invisible players issue

### ISSUE THREAD

**Issue by EternalHuman** [tr7zw/EntityCulling#136]
![image](https://github.com/tr7zw/EntityCulling/assets/71584363/f2906777-1bb9-444f-ac05-f05eadb27ef9)
a) now it's vanilla
b) this is not hack client, lol. 
![image](https://github.com/tr7zw/EntityCulling/assets/71584363/3b543dcc-30a8-4c1e-b8b9-92302490b4e5)

https://www.youtube.com/results?search_query=eternal+jedicraft

**Comment by EternalHuman** [comment]
![image](https://github.com/tr7zw/EntityCulling/assets/71584363/dc9698fb-c76e-4a68-a5cf-f36ceeae731f)
That's the reason for this.

**Comment by tr7zw** [comment]
![grafik](https://github.com/tr7zw/EntityCulling/assets/5133936/39790387-2074-49dd-90a4-2cc6ab16065f)
It's not vanilla, stop opening new issues. If the tickculling is broken, then it's because of that mod.

**Comment by EternalHuman** [comment]
lol

**Comment by EternalHuman** [comment]
![image](https://github.com/tr7zw/EntityCulling/assets/71584363/60d2c662-dd4e-46bc-a1e3-7fb46064a90f)

Just renamed Forge 1.16.5 man

**Comment by tr7zw** [comment]
https://github.com/tr7zw/EntityCulling/assets/5133936/5e40ceec-ccca-4abd-8d0a-5dc3e3353905

**Comment by EternalHuman** [comment]
> qHrWVCGIgG.mp4

This happens 1 time out of 5

**Comment by EternalHuman** [comment]
Looks like OptiFine issue

**Comment by tr7zw** [comment]
So much to vanilla. Optifine is basically not tested anymore. It's 2024.

**Comment by EternalHuman** [comment]
100% OptiFine issue
![image](https://github.com/tr7zw/EntityCulling/assets/71584363/c11b4b6a-7b2c-431a-9886-354d7412cba4)

**Comment by EternalHuman** [comment]
> So much to vanilla. Optifine is basically not tested anymore. It's 2024.

It provides many new opportunities in the field of texture packs

**Comment by tr7zw** [comment]
> It provides many new opportunities in the field of texture packs

Optifine has been 100% replaced, even better. There is no reason to use it unless you run some 14+ year old laptop or something. With a RTX3060 you are just throwing away performance and features by using it.

**Comment by EternalHuman** [comment]
> > It provides many new opportunities in the field of texture packs
> 
> Optifine has been 100% replaced, even better. There is no reason to use it unless you run some 14+ year old laptop or something. With a RTX3060 you are just throwing away performance and features by using it.

I can't use custom entity models in texturepacks with Sodium.

**Comment by tr7zw** [comment]
https://modrinth.com/mod/entitytexturefeatures https://modrinth.com/mod/entity-model-features Even packs like Fresh Animations shouldn't be used with Optifine at this point.

**Comment by EternalHuman** [comment]
> https://modrinth.com/mod/entitytexturefeatures https://modrinth.com/mod/entity-model-features Even packs like Fresh Animations shouldn't be used with Optifine at this point.

1.18.2+

**Comment by tr7zw** [comment]
>  It's 2024.

Servers either support all the versions past 1.8, or are on modern versions. Don't think there are servers that are 1.16.5 only(without 1.18/1.19/1.20 support).
