### ISSUE TITLE
1.7.10 Incompatibility between EntityCulling and Thaumcraft

### ISSUE THREAD

**Issue by harvald** [tr7zw/EntityCulling#144]
[crash-2024-03-27_18.43.29-client.txt](https://github.com/tr7zw/EntityCulling/files/14780522/crash-2024-03-27_18.43.29-client.txt)

Crash happened multiple times when entering nether, where wisps are in abundance. Stop crashing after removing EntityCulling mod.

**Comment by tr7zw** [comment]
> java.lang.ClassCastException: thaumcraft.client.renderers.entity.RenderWisp cannot be cast to dev.tr7zw.entityculling.mixin.RenderLivingEntityAccessor
	at net.minecraft.client.renderer.entity.RenderManager.handler$zbj000$entityculling$doRenderEntity(RenderManager.java:531)

Uhhh I guess that is some side effect due to the Wisp not being a real entity. Should be easy to fix.

**Comment by ghost** [comment]
In the meantime can this be fixed by whitelisting `entity.Thaumcraft.Wisp` (and `entity.TwilightForest.Firefly` for #145)?

Edit: Just realised that whitelist might be for blocks that you can actually see through - not sure.

**Comment by tr7zw** [comment]
Fixed with #145.
