### ISSUE TITLE
Crashes on launch with modpack with Pollution of the Realms (adpother) [1.12.2]

### ISSUE THREAD

**Issue by Molthus** [tr7zw/EntityCulling#146]
I added this to a modpack and found I could no longer launch the game without crashing. The crash log seems to point to some incompatibility with Pollution of the Realms (adpother) [found here: https://www.curseforge.com/minecraft/mc-mods/pollution-of-the-realms].

It seems there is some other third thing involved here, though, as running a fresh install with just Pollution of the Realms and this mod did not result in a crash.

The modpack can launch and run without this mod, so it isn't exclusively an incompatibility between Pollution of the Realms and something else in the pack; it was adding this mod that started the crashing for the overall pack.

Please let me know if there's anything I can do to help speed along a possible fix!

Crash log attached below:
[latest.log](https://github.com/tr7zw/EntityCulling/files/14915519/latest.log)

**Comment by tr7zw** [comment]
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method setBlockStateInjectGenerateSkylightMapVanilla(Z)Z in mixins.phosphor.json:common.MixinChunk$Vanilla from mod unknown-owner failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.phosphor.refmap.json

This is phosphor crashing.

**Comment by Molthus** [comment]
Thank you for the speedy reply! On testing, removal of Phosphor did allow the game to launch with EntityCulling!

Is this something I should report to the Phosphor crew, then?

**Comment by tr7zw** [comment]
I'm more surprised that there is a Phosphor version for 1.12. Phosphor is from JellySquid, afaik mostly ™️ dead(no update in 2 years), and JellySquid hasn't been making mods for Forge for 4 years or so. I just found this https://modrinth.com/mod/phosphor-crash-fix which might fix it, but if that doesn't help, just kick out Phosphor.

**Comment by Molthus** [comment]
That worked, my performance in a densely built area has now gone from ~20 fps average to ~40, thank you so much!
