### ISSUE TITLE
Doesn't seem to be culling all invisible entities

### ISSUE THREAD

**Issue by dylanparry** [tr7zw/EntityCulling#148]
![image](https://github.com/tr7zw/EntityCulling/assets/3692873/e83b24c0-b931-4edd-b154-c1693d741988)

As you can see from the screenshot, I'm facing a wall, so there shouldn't be any entities rendered, yet it's still rendering 38. This number goes up and down a lot. It's been as low as 19 and as high as 60, without me moving from this spot at all.

The only thing that reduces it is turning my render distance down. I currently have it set at 30 (as I'm using Nvidium) and it has no problem maintaining 60fps for the most part, but when the number of entities gets really high then I start to lose FPS. I've gone through my mods and disabled them one at a time, but I haven't found one that is causing this to happen.

Using Minecraft 1.20.4 and mod version 1.6.4-1.20.4. Here's a list of my other mods:

    *  AmbientSounds_FABRIC_v5.3.5_mc1.20.4.jar 
    *  better-clouds-1.5.7+1.20.4.jar 
    *  BetterF3-9.0.2-Fabric-1.20.4.jar 
    *  BetterPingDisplay-Fabric-1.20.4-1.1.1.jar 
    *  blur-3.2.0.jar 
    *  Boat-Item-View-Fabric-1.20.1-0.0.5.jar 
    *  cave_dust-1.4.1.jar 
    *  Chunky-1.3.138.jar 
    *  clean_tooltips-1.0-fabric-1.20.4.jar 
    *  cloth-config-13.0.121-fabric.jar 
    *  continuity-3.0.0-beta.4+1.20.2.jar 
    *  CreativeCore_FABRIC_v2.11.16_mc1.20.4.jar 
    *  DistantHorizons-fabric-2.0.2-a-dev-1.20.4.jar 
    *  DripSounds-1.19.4-0.3.2.jar 
    *  dynamic-fps-3.4.2+minecraft-1.20.4-fabric.jar 
    *  emissive-plugin-1.20.4-2.0.4-fabric.jar 
    *  enhancedblockentities-0.9.1+1.20.2.jar 
    *  entityculling-fabric-1.6.4-mc1.20.4.jar 
    *  entity_model_features_fabric_1.20.4-1.3.jar 
    *  entity_texture_features_fabric_1.20.4-5.2.3.jar 
    *  fabric-api-0.96.11+1.20.4.jar 
    *  fallingleaves-1.15.6+1.20.1.jar 
    *  ferritecore-6.0.3-fabric.jar 
    *  ForgeConfigAPIPort-v20.4.3-1.20.4-Fabric.jar 
    *  held-item-info-1.5.0.jar 
    *  HorseBuff-1.20.2-2.1.3.jar 
    *  ImmediatelyFast-Fabric-1.2.11+1.20.4.jar 
    *  indium-1.0.30+mc1.20.4.jar 
    *  MapTooltip-fabric-1.20-3.0.0.jar 
    *  modernfix-fabric-5.15.0+mc1.20.4.jar 
    *  modmenu-9.1.0-beta.1.jar 
    *  moreculling-1.20.4-0.22.1.jar 
    *  moremcmeta-1.20.4-4.4.7-fabric.jar 
    *  notenoughanimations-fabric-1.7.1-mc1.20.4.jar 
    *  nvidium-0.2.6-beta.jar 
    *  PickUpNotifier-v20.4.2-1.20.4-Fabric.jar 
    *  PresenceFootsteps-1.11.3.jar 
    *  PuzzlesLib-v20.4.42-1.20.4-Fabric.jar 
    *  reeses_sodium_options-1.7.2+mc1.20.4-build.102.jar 
    *  show-me-your-skin-1.8.0+1.20.4.jar 
    *  shulkerboxtooltip-fabric-4.0.8+1.20.4.jar 
    *  skinlayers3d-fabric-1.6.2-mc1.20.4.jar 
    *  sodium-extra-0.5.4+mc1.20.4-build.116.jar 
    *  sodium-fabric-0.5.8+mc1.20.4.jar 
    *  sound-physics-remastered-fabric-1.20.4-1.3.1.jar 
    *  tia-1.20-1.1-fabric.jar 
    *  too-cheap-1.2.0.jar 
    *  voicechat-fabric-1.20.4-2.5.12.jar 
    *  where-are-we-now-1.1.0.jar 
    *  yet-another-config-lib-fabric-3.3.2+1.20.4.jar 

Any ideas?

**Comment by tr7zw** [comment]
First of all, some entities will still be rendered/processed. That's normal. Also without the f3 info of the mod there is nothing I can say. Temporarily disable BetterF3(or re-enable that it shows the actual info) to see whats going on.

**Comment by dylanparry** [comment]
Apologies :)

Is this more useful?

![image](https://github.com/tr7zw/EntityCulling/assets/3692873/865271ea-42ab-4f36-aaea-8ee467d40b3b)

**Comment by tr7zw** [comment]
Just looks like the rendered number displayed by BetterF3 is wrong: 7 rendered entities, 37 skipped(to be fair, so might be the vanilla one, that's what the extra Culling line is for in F3^^). Also, the higher rendered block entities (76, only 12 skipped) are probably due to enhancedblockentities replacing the chests/signs/shulkers that might be behind that wall.

**Comment by dylanparry** [comment]
Thanks for the info. There are a load of chests etc behind me, but nothing in front just water. I'll see what happens when I disable Enhanced Block Entities and also disable Better F3 to see if the numbers are the same.

**Comment by tr7zw** [comment]
You can bind the debug toggle key for entityculling in the settings, then you'll see how the performance changes in realtime. Also, you might be able to see in the f3 pi chart what exactly is rendering there.

**Comment by dylanparry** [comment]
Thanks, that's helped. I can see it's definitely working at least. Do you think the reason I'm seeing a high number could be because I've got a render distance higher than 8 chunks (128 blocks) and that's as far as the mod looks? If I reduce the render distance to 8 chunks, then the number of entities drops drastically, so maybe those extra entities are between 128 and 512 blocks away where the mod isn't looking?

**Comment by dylanparry** [comment]
I think I've tracked down my issues to the Distant Horizons mod. When I disable it everything works beautifully. Sorry to have bothered you :D
