### ISSUE TITLE
(b1.7.3) Entities not rendering correctly

### ISSUE THREAD

**Issue by Karpatok9089** [tr7zw/EntityCulling#149]
Cows and sheeps doesn't render correctly, they're missing their head and only has 3 legs.
![2024-04-14_14 12 13](https://github.com/tr7zw/EntityCulling/assets/110969697/4312442c-c073-4a97-9ba0-ce4961fbecfd)

Either because entity culling is broken or because I use Far View+Far render distance, which causes lag (I'm using Optifine HD MT G2 btw)

**Comment by tr7zw** [comment]
Entity culling doesn't touch the model rendering in any way. Either the mob is rendered or it's not. Body parts missing is impossible to be caused by it.
