### ISSUE TITLE
Incompatibility with Distant Horizons

### ISSUE THREAD

**Issue by K-eistra** [tr7zw/EntityCulling#154]
I Checked solved and unsolved issues and it doesnt seem to have been reported previously so if possible could you look into somehow whitelisting distant horizons lod blocks so that they load? 
outside of default render distance at the moment there is nothing shown when using entityculling and distanthorizons...
If i am being dumb in some way then please let me know and ill close my case asap.

**Comment by K-eistra** [comment]
I somehow retested and it seems to be working for me now.... sorry to bother you as it seems to somehow be alexs caves disturbing the distant lodding...

**Comment by tr7zw** [comment]
I was confused seeing this issue, as distant horizons should have nothing to do with this mod.

**Comment by K-eistra** [comment]
Yeah sorry about that, I was doing some testing and when I thought I only disabled the entityculling mod I must have somehow also disabled alexs caves at the same time without realizing which led to the distant chunks loading again. This led me to believe that entityculling had an incompatibility issue. I thought it kinda made sense since entityculling was about not rendering stuff that isn’t seen and considering the distant chunks are sort of loaded outside the default render distance it might have been the issue, but yeah. It wasn’t… My bad.
