### ISSUE TITLE
Question: Do I need to disable Sodium culling settings?

### ISSUE THREAD

**Issue by TheCrossCarrier** [tr7zw/EntityCulling#156]
Sodium has settings for culling entities and block faces. Do I need to disable any of these when using with your mod?

**Comment by tr7zw** [comment]
From the modpage:
![grafik](https://github.com/tr7zw/EntityCulling/assets/5133936/f5081435-481d-4eab-914c-6ac9a420041c)

**Comment by TheCrossCarrier** [comment]
Thanks, I read the modpage. But I asked if I should turn this Sodium feature OFF or if it should be ON. The question was: what is better from your point of view, to enable the culling function in Sodium or not (using it with your mod)?

**Comment by tr7zw** [comment]
Just leave it ON. There is no reason to turn it off or ever change that setting.
