### ISSUE TITLE
Sodium's option with entity culling mod

### ISSUE THREAD

**Issue by HassaanBG** [tr7zw/EntityCulling#159]
For the best fps. Should I keep the sodium's entity culling option to on while using this mod or instead should I turn it off?

**Comment by tr7zw** [comment]
Duplicate #156 #132 #40 also explained on the modpage
![grafik](https://github.com/tr7zw/EntityCulling/assets/5133936/ee0651ea-9bfc-4397-b1ea-2cd19312ab87)
