### ISSUE TITLE
Chisel and bits incompatibility

### ISSUE THREAD

**Issue by Henkaeru** [tr7zw/EntityCulling#165]
Chiselled blocks from the mod Chisel and bits are unaffected by the block entity culling.

A screenshot showing the setup:

![image](https://github.com/user-attachments/assets/a0d11c9f-f0ec-448a-a450-27feb4d8a890)

A screenshot showing the entity culling not working on chiselled blocks while working on other block entities:

![image](https://github.com/user-attachments/assets/916f9f43-8227-45f3-b852-8008dc8528e7)

**Comment by tr7zw** [comment]
I'm not 100% sure, but pretty decent chance that these are just not block entities(or rendered as such)? At least that would hurt performance like hell if they got rendered like vanilla chests/signs etc.

**Comment by tr7zw** [comment]
Also, are you using distance + zoom to check that they get culled? That has nothing to do with entityculling, thats just the vanilla block entity render distance of I think 32.

**Comment by Henkaeru** [comment]
For this test, I'm using OrthoCamera (yeah, pretty strange way of testing. But it is using entity culling, my character is at the other side of the wood wall, and when stepping out, the blocks reappear).

**Comment by Henkaeru** [comment]
I'm not exactly sure it's a block entity. I can't find the exact information, and I don't really want to have a look at the messy code that is chisel and bits.
But many things point to it being a block entity.

First and foremost, using /data get block on a block:

![image](https://github.com/user-attachments/assets/9266bd4f-8fa4-4878-b6ca-022d93426cee)

using it on a chiselled block:

![image](https://github.com/user-attachments/assets/8b1fc5da-fd4d-40a7-8d4d-e4d1611f25d3)

Also, the creator of little tiles (chisel and bits but better and forge-only) made this video where he shows a performance increase by fixing a vanilla bug with tiles entities and talking about his blocks as a tile entity:

https://www.youtube.com/watch?v=vTCJbp45pWM

In a comparison video, he talks about chiselled blocks and little tiles blocks as tiles entities. In the description, he also asks himself if chisel and bits fix the above-mentioned issue:

https://www.youtube.com/watch?v=mv08_5iWy1Q

Also, CraftTweaker when using /ct block_info talk about chiselled blocks as being block entities while not doing so on other blocks:

on sand block:

![image](https://github.com/user-attachments/assets/937eab65-9b7b-48ee-8283-804162296a06)

on chiselled block:

![image](https://github.com/user-attachments/assets/f117f723-a61f-4931-8702-6ad43308d4d8)

In this old issue of chisel and bits, chiselled blocks are considered as tile entities:

https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/205



In the end, I'm sure it's not a block, but I'm not sure if it's a tile entity, maybe some other strange state ? But even if they're not exactly tile entities, maybe it's possible to make it compatible by considering chiselled blocks as tile entities (I have no clue) seeing how similar they are (if they are not actually tile entities).

**Comment by Henkaeru** [comment]
And they do hurt performance pretty bad, that's why it would be great to have them be compatible with EntityCulling. This mod is known to be the doom of any modded world…

**Comment by tr7zw** [comment]
Hm, then they render via some custom render logic (that would make sense, since a house made out of chiseled blocks otherwise would nuke performance). But that means they don't render like a normal block entitiy, so there is nothing EntityCulling can do (it probably sets them to not render, but they still do due to the other logic).
