### ISSUE TITLE
Axolotl swims sideways (and sometimes backwards) 

### ISSUE THREAD

**Issue by PixalThePixeled** [tr7zw/EntityCulling#166]
The axolotls sometimes faces the wrong way while they swims.

![2024-08-22_21 48 14](https://github.com/user-attachments/assets/40645b53-dc23-4bfa-a700-6e18b95b0ce9)
![2024-08-22_21 48 28](https://github.com/user-attachments/assets/a7020597-320e-49c0-8dbe-94e7df7e196f)

When I pull them out onto land, they return to their normal state, but after immersion in water they may again begin to swim unevenly (This may happen gradually over time).

- Minecraft Version: Fabric 1.20.4
- Installed mods:
  - Fabric Api
  - ModMenu
  - EntityCulling

**Comment by tr7zw** [comment]
And how did you determine that this is a bug of this mod? Of screen entities get their animations skipped, but that should fix itself on the first tick of being visible. Extended effects caused by this like entities being rotated the wrong way is not heard of so far.  (did you try without mods)

**Comment by PixalThePixeled** [comment]
I tested one by one all the mods that I had installed and found out that this happens with the Entity Culling mod and exactly when they swim, without it the axolotls are always facing the eye line, just like in vanilla

**Comment by tr7zw** [comment]
https://bugs.mojang.com/browse/MC-225859 This is a vanilla bug
