### ISSUE TITLE
Rare case where entities are null and Entity iterator counter go nuts :zany_face: 

### ISSUE THREAD

**Issue by pietro-lopes** [tr7zw/EntityCulling#168]
To reproduce this you might need to keep going through other dimension and going back very fast.
I managed to get this while on creative and going to nether and going back.
May take a while

I managed to capture a moment where entity was null and the iterator goes in infinite loop (hasNext returns always true)

https://github.com/tr7zw/EntityCulling/blob/4ee31d51d0ad2481dbd6296cd1fb3625b6dfe95f/src/main/java/dev/tr7zw/entityculling/CullTask.java#L95

here is a sequence of images **where it first hits null**
![null2](https://github.com/user-attachments/assets/eb9b1b6f-ed01-4834-9a6d-6351fb1ed1ff)
![null3](https://github.com/user-attachments/assets/30405c2d-d81e-43e5-9c73-907dea36ea2e)
![null4](https://github.com/user-attachments/assets/5dfc3f2d-a84c-4de5-b2bd-329b66b4e698)

and so on, `index` goes until it hits max int and goes into negative

This causes CullThread to get stuck in this infinite while loop.

**Comment by tr7zw** [comment]
AHHHHH I did experience this issue before and even managed to attach a profile, but that didn't allow me to see memory values, just that the stack seemed to move in a normal way around the thread, so I had no clue why it was behaving weirdly and fixing itself after some time (I assumed the thread crashed/deadlocked/got stuck on something, which wasn't the case). Amazing catch, will publish fixed versions later today.

**Comment by tr7zw** [comment]
Adding the simple workaround right now, 
> hasNext returns always true

this is really interesting. I fully expect getting null/ConcurrentModificationException/ArrayIndexOutOfBoundsException when iterating over the entity list in this unsafe non thread safe way, but the iterator overshooting and going through the entire int value space is certainly a new (and unexpected) one. I'll change it to instead break the loop when it gets a null value after hasNext was true.
