### ISSUE TITLE
Slowing down elytra boost from fireworks

### ISSUE THREAD

**Issue by RLGCamille** [tr7zw/EntityCulling#169]
Using fireworks to boost elytras is way slower with this mod enabled, disabling this mod makes elytras with fireworks work normally, otherwise fireworks act as a bounce rather than a boost.

**Comment by tr7zw** [comment]
Then you probably messed with the config file. Delete it and let it regenerate to a correct state where fireworks are excluded from the mod.

**Comment by tr7zw** [comment]
Closing due to inactive. When fireworks are correctly whitelisted, this shouldn't happen.
