### ISSUE TITLE
A hard-coded name is used instead of the translation key

### ISSUE THREAD

**Issue by Tapacywka** [tr7zw/EntityCulling#172]
I'm working on a resourcepack containing translations of settings menus from different mods into other languages (currently US, UA and RU), and I've noticed that instead of a translation key in the mod name, a hard-coded name is used, so I can't interact with it during the translation. Is it possible to output a separate translation key for the mod name in the language file like all other mods do?

![image](https://github.com/user-attachments/assets/c006a4ca-68cb-4aeb-b164-824d34fd86de)

**Comment by Thijzert123** [comment]
The "Firstperson" isn't from this mod, but I can fix the EntityCulling one.
