### ISSUE TITLE
Fabric 1.21.3: Game loading screen is stuck

### ISSUE THREAD

**Issue by trueddd** [tr7zw/EntityCulling#177]
After launching the game, loading screen gets stuck but the main menu seems to be active. I can randomly hit the button and hear buttons sounds.

Game launches fine with Entity Culling mod disabled.

Screenshot:
![image](https://github.com/user-attachments/assets/8b59b073-a033-4aee-908a-f587f88db9f7)

Minecraft version - 1.21.3
Fabric loader version - 0.16.9

List of enabled mods:
| Mod | Version |
|------|----------|
| Architectury API | 14.0.4+fabric |
| Cloth Config API | 16.0.141+fabric |
| Entity Culling | 1.7.0 |
| Fabric API | 0.107.0+1.21.3 |
| Hey Wiki | v1.7.1+1.21.1-fabric |
| Iris Shaders | 1.8.0-beta.6+1.21.2-f |
| Mod Menu | 12.0.0-beta.1 |
| Sodium | mc1.21.3-0.6.0-beta.4-fabric |
| Sodium Extra | mc1.21.3-0.6.0-beta.4-fabric |
| Text Placeholder API | 2.5.0+1.21.2 |

**Comment by tr7zw** [comment]
There is no 1.21.3 version released, so of cause it doesn't load.
