### ISSUE TITLE
[1.12.2] entityculling.mixins.json:CullableMixin was loaded too early

### ISSUE THREAD

**Issue by X-XLebyshek** [tr7zw/EntityCulling#178]
Forge: 14.23.5.2860
Entity Culling 1.6.3
Sooo there is no crash-report, it crashes too early, but the console gives me some information, namely:

Critical problem: entityculling.mixins.json:CullableMixin from mod unknown-owner target net.minecraft.entity.Entity was loaded too early.
_Or_
Mixin [entityculling.mixins.json:CullableMixin from mod unknown-owner] from phase [DEFAULT] in config [entityculling.mixins.json] FAILED during PREPARE
I suspect it's because the mixin was loaded too early, as it states, so ima probably install Mixin Compat... Oh wait! I already have it installed!

So help pls
Also, interestingly, the _same_ problem happens with the other EntityCulling mod by Meldexun

**Comment by tr7zw** [comment]
Mixins can't load too early. They need to be loaded when the classes load, thats it. Sounds more like your Mixin loader mod has an issue. Also the latest log is the crash report in that case.
