### ISSUE TITLE
Add a notification when toggling entity culling

### ISSUE THREAD

**Issue by Wxrlds** [tr7zw/EntityCulling#18]
Currently when you toggle entity culling it can be really hard to tell if you turned it off or on.
I suggest to add a message over the inventory that tells you if culling is enabled or disabled (I think it's called action bar, the thing that shows up if you try to sleep in a bed during day)

**Comment by tr7zw** [comment]
I mean you can see that "skipped" is 0 for everything in F3, but yea I can add a chat message.
