### ISSUE TITLE
FEATURE REQUEST: Upload to Modrinth

### ISSUE THREAD

**Issue by edwloef** [tr7zw/EntityCulling#30]
Modrinth is a website for fabric mods specifically, and most of my performance enhancing mods have been uploaded there. It would be nice to see it there as well!

https://modrinth.com/

**Comment by tr7zw** [comment]
Currently not planning to release on modrinth. They don't yet have comparable stuff to the Curse rewards program, and only about 3% of the mods have even 1000 downloads(namely only 23 mods). In the meantime, on Curse, I can use the rewards program, and have everything (also the forge stuff) in one place and let it grow together and eat less time than maintaining multiple websites, while also having a far bigger reach.
When modrinth has matured more then this will be something else.

**Comment by Xrey274** [comment]
> Currently not planning to release on modrinth. They don't yet have comparable stuff to the Curse rewards program, and only about 3% of the mods have even 1000 downloads(namely only 23 mods). In the meantime, on Curse, I can use the rewards program, and have everything (also the forge stuff) in one place and let it grow together and eat less time than maintaining multiple websites, while also having a far bigger reach.
> When modrinth has matured more then this will be something else.

Now it's 41 mods with >=1000 downloads.

**Comment by tr7zw** [comment]
> Now it's 41 mods with >=1000 downloads.

Yea and on Curse I have over 1.1 million downloads. 
Just last week I used the rewards from the Curse program to buy presents for my Sister, replacement parts for my car and tools to fix old Gameboy games and still have reward points left over. So putting in the time to bring and maintain everything on modrinth too, currently just isn't worth it.

**Comment by Xrey274** [comment]
No, fully get you. Point of the "now it's 41 mods" was that the site is growing.

**Comment by tr7zw** [comment]
I mean yea, and like I said, if it gets big enough/something happens to Curse then there is no issue to upload it to Modrinth. Always good to have a fallback just in case something bad does happen to Curse, but thankfully it is no longer owned by Twitch, so stuff actually progresses(see added Fabric support, better multi modloader support etc).

**Comment by itsdinkd** [comment]
Curse also consistently breaks fabric filtering, mods, and modpacks. They constantly have bugs that will remove the fabric tag making mods impossible to find on curseforge launcher unless you manually look on the website.

**Comment by tr7zw** [comment]
Gave Modrinth a try now with one mod and a few versions:
 - File upload is broken and it takes multiple minutes to upload a single file thanks to server errors
 - Download counter is broken and just stuck at 0(with 16 followers), so far no response on Discord
 - Any time I edit the page I have to re-fill-in the license field cause it doesn't save properly

I think Modrinth probably might just not be production-ready.
When they are further in their features like Creator analytics, Creator payouts, or bug fixes I'll give it a try again.
![grafik](https://user-images.githubusercontent.com/5133936/167164118-01c6c29a-d549-49ce-bf36-1e50aa1eb25f.png)

Less important issues:
 - In regards to the comment above, currently, the modloader filtering on Modrinth is broken thanks to Quilt apparently
 - Missing dependency graphs
 - Inconsistent versions page filters(auto selects fabric, shows forge versions)
 - Current version seems to have some issues with Google?(not showing up at all/showing up without any text)

**Comment by tr7zw** [comment]
https://modrinth.com/mod/entityculling Since Curse fucked up the API too hard, I did upload it to Modrinth. The download counter issue was fixed by re-uploading the files and losing 2 weeks of stats, but I guess that's still better than CurseForges API mess...
