### ISSUE TITLE
Loses track of mobs and leaves them invisible.

### ISSUE THREAD

**Issue by CodeF53** [tr7zw/EntityCulling#31]
(not sure if the 1.18 worldgen data pack is supported or not, but this wasn't an issue in the last version)

When the player is at y<0, entities no longer render with the new update.

video: https://www.youtube.com/watch?v=Isoc7XUqdP4

**Comment by CodeF53** [comment]
(only happens in 1.3.1, not 1.3)

**Comment by tr7zw** [comment]
That's especially odd, because 1.3.1 does nothing to the culling, compared to 1.3.0. I'll look into it.

**Comment by tr7zw** [comment]
![grafik](https://user-images.githubusercontent.com/5133936/124365428-38955980-dc48-11eb-9d34-9a8e649ca379.png)
I can't reproduce it with the 1.3.1 version. Can you try to more directly reproduce it? Also was that singleplayer or multiplayer?

**Comment by CodeF53** [comment]
it was in singleplayer, with sodium and iris.

let me try reproducing it in a creative world.

**Comment by tr7zw** [comment]
![grafik](https://user-images.githubusercontent.com/5133936/124365717-0ab11480-dc4a-11eb-8571-4b8177bdad4c.png)
Hm same with iris + sodium.

**Comment by CodeF53** [comment]
I recreated what I was doing at the time in my world, cant put my setup into words.

sodium 0.3.0 IRIS-rev.7491e3a
   \- https://modrinth.com/mod/iris/version/lQjKfhXZ
entityculling 0.3.1
Tweakaroo with gamma override on

seed: 2340225447661560456
coords: 850 -25 526

https://www.youtube.com/watch?v=xYoRO9Zywvs

**Comment by CodeF53** [comment]
After further testing, I have found that:
- This has nothing to do with negative coordinates
- It 100% only happens in 1.3.1
- It happens in vanilla, with no other mods loaded
- It is brutally simple to replicate.

Here is a gif of me replicating the issue:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/37855219/124521716-d22a4b80-ddad-11eb-9416-6e6cd77cf73b.gif)

Here is the world download so you can replicate it yourself.
[EntityCulling-Iss#31.zip](https://github.com/tr7zw/EntityCulling-Fabric/files/6766370/EntityCulling-Iss.31.zip)

**Comment by tr7zw** [comment]
Huh thanks, I'll give it a try with that world to figure out what the hell happens there.

**Comment by tr7zw** [comment]
https://github.com/tr7zw/EntityCulling-Fabric/actions/runs/1015796246
This build should fix that, at least I wasn't able to reproduce it anymore.

**Comment by akasnowmaaan** [comment]
I think this may be the same issue, so I'm posting here instead of opening another one.

I am experiencing mobs disappearing right in front of me in the newest version. A tamed dog that disappears if I stand 7-8 blocks away, and it's reproducible at will. Once it disappears, I have to walk from 2-8 blocks from my initial position to make the dog reappear.

Here are screenshots to demonstrate.

- First one is without EntityCulling running.
![2021-07-18_20 32 47](https://user-images.githubusercontent.com/3442392/126078759-8f0616a7-4ddc-4afc-8d5b-eb6bd336e352.png)

- Second is the same situation with it running.
![2021-07-18_20 40 06](https://user-images.githubusercontent.com/3442392/126078764-5bb3735d-6772-4a57-9876-28627da292d6.png)

- I can walk around and it's still invisible.
![2021-07-18_20 40 27](https://user-images.githubusercontent.com/3442392/126078854-a2cbad53-6cd4-46df-b9b3-11167371c036.png)

My setup:
1.17.1, Fabric. Happens with or without the newest Sodium running.

**Comment by tr7zw** [comment]
Which version of the mod?

**Comment by akasnowmaaan** [comment]
> Which version of the mod?

Latest on Github - 1.3.3 - downloaded and installed today

**Comment by DigitalWendigo** [comment]
I know it's been a while since this issue, but..
I'm having the same issue with the dog. 
I'm also using optifine, which might be also responsible. 
I'm using EntityCulling [1.5.1 - Forge(1.16)] on Minecraft 1.16.5
OptiFine version HD_U_G8
Also using Performant, latest update.

**Comment by tr7zw** [comment]
Performant is not tested at all, pretty sure it's because of that. Not planning to add support for it, since it's just old forge versions.

**Comment by DigitalWendigo** [comment]
Got it, I'll ask them then. Thanks for the quick reply!

**Comment by tr7zw** [comment]
Hm looks like they are working on 1.17/1.18 versions, issue then becomes that it's closed source. So yea, would have to reproduce this and then can't even look at what's going on.

**Comment by DigitalWendigo** [comment]
There is another entity culling mod made by meldexun, which strangely enough does not produce this issue. 
I'm not entirely sure why, but they seem to be doing something different that causes issues like this to not occur. 
Perhaps they might be able to help you with this issue in some way? 
Just a thought.

**Comment by CodeF53** [comment]
@DigitalWendigo

This issue was fixed ages ago. If you are having it now, please open a new issue, don't resurrect old ones.

**Comment by tr7zw** [comment]
The comment is about a conflict with Performant, a closed source legacy forge mod. For now I think it's use one or the other(or filter out all affected mobs in the config file).
