### ISSUE TITLE
Passengers

### ISSUE THREAD

**Issue by andreasdc** [tr7zw/EntityCulling#32]
Mod doesn't hide passengers riding on hidden players like stacker

**Comment by tr7zw** [comment]
Are you maybe looking for the Spigot plugin? Or can you post an image of the issue?

**Comment by andreasdc** [comment]
> Are you maybe looking for the Spigot plugin? Or can you post an image of the issue?

mod*

**Comment by tr7zw** [comment]
Then I can't quite follow your issue. Entities riding on players are not hidden?

**Comment by andreasdc** [comment]
Exactly.

**Comment by andreasdc** [comment]
Not only not hidden, but bugged.

**Comment by tr7zw** [comment]
Can you please show a picture/video of that? Normally each entity on the stack should be culled on its own.

**Comment by tr7zw** [comment]
But thinking about it, are you perhaps using the 1.3.1 build instead of 1.3.0?

**Comment by andreasdc** [comment]
EntityCulling-Fabric-1.3.1 1.17

**Comment by tr7zw** [comment]
Ok then I might have an idea to what this is. If you are playing on a server that actively does that, you can for now disable tick culling in the config/use 1.3.0.

**Comment by andreasdc** [comment]
On 1.3.0 I don't see this problem. Do you add entity track limit?

**Comment by tr7zw** [comment]
It skips ticking entities you can't see. The issue is that when they are stacked and the "main" entity moves away while hidden, the others probably hang back in the air. Will have to modify that riding entities never get skipped.

**Comment by andreasdc** [comment]
@tr7zw how to check if it's working? Will increasing sleepDelay help?

**Comment by andreasdc** [comment]
> It skips ticking entities you can't see. The issue is that when they are stacked and the "main" entity moves away while hidden, the others probably hang back in the air. Will have to modify that riding entities never get skipped.

Wouldn't it be better to hide riders too?

**Comment by tr7zw** [comment]
> @tr7zw how to check if it's working? Will increasing sleepDelay help?

What do you mean? This needs to be fixed in the next release, you can just turn of the feature or use the 1.3.0 that doesn't yet contain that.

**Comment by andreasdc** [comment]
I wanted to see if they actually hide, I changed delay to 1000 and now it's noticable. I was asking will increasing this delay help in performance?

**Comment by tr7zw** [comment]
You can use the debug setting for that, it binds the culling to the player instead of the camera, so you can use F5 to look around corners.

**Comment by tr7zw** [comment]
And you can increase the delay if you don't have many cpu cores. The culling happens async, so as long as the cpu has any other headroom, it will not negatively impact the performance.

**Comment by andreasdc** [comment]
debugMode false still shows on f3 informations

**Comment by andreasdc** [comment]
@tr7zw do you plan to fix this tick culling? I would want to cull entites, but not when they are bugged in place :D

**Comment by tr7zw** [comment]
Had multiple final presentations for University lectures this week, now I'm done with that and can take a look.

**Comment by andreasdc** [comment]
@tr7zw sure, good luck ❤️

**Comment by tr7zw** [comment]
https://github.com/tr7zw/EntityCulling-Fabric/actions/runs/1015796246
Please give this build a try, it fixed at least the #31 issue.

**Comment by andreasdc** [comment]
@tr7zw i'm testing it right now, still bugged.

**Comment by tr7zw** [comment]
So normal entities update their position correctly, living entities via their movement tick except when they are riding another entity... awesome. Guess for now I'll just whitelist riding entities?

**Comment by andreasdc** [comment]
@tr7zw like the best effect would be to hide riding entitie too, right?

**Comment by andreasdc** [comment]
@tr7zw also 
https://github.com/tr7zw/EntityCulling-Fabric/blob/686e423ac5d63c42244300de173e46ba220f5e0a/src/main/java/dev/tr7zw/entityculling/CullTask.java#L108
128 shouldn't be replaced with value from config?

**Comment by tr7zw** [comment]
Hide != ticked. For example, I always tick the vehicle of the player, no matter the visibility. Since I still don't know the exact setup that you have there without a screenshot(or how the bug looks like), I can just guess fix it^^. I'll quickly make a commit where riding entities always have a full tick no matter what. 


> 128 shouldn't be replaced with value from config?

Well yes and no. That value is the hard cutoff to quickly skip too far away entities. Technically that value should be the entity view distance form the settings menu.

**Comment by tr7zw** [comment]
https://github.com/tr7zw/EntityCulling-Fabric/actions/runs/1016009138
Basically, that should make stacked entities behave like in 1.3.0.

**Comment by andreasdc** [comment]
> Hide != ticked. For example, I always tick the vehicle of the player, no matter the visibility. Since I still don't know the exact setup that you have there without a screenshot(or how the bug looks like), I can just guess fix it^^. I'll quickly make a commit where riding entities always have a full tick no matter what.
> 
> > 128 shouldn't be replaced with value from config?
> 
> Well yes and no. That value is the hard cutoff to quickly skip too far away entities. Technically that value should be the entity view distance form the settings menu.

I have 128 on the server.
Shouldn't riding entities also be hidden when their vehicle is hidden?

**Comment by tr7zw** [comment]
> Shouldn't riding entities also be hidden when their vehicle is hidden?

No. If you stack 10 entities and only see the top 5, only they should be visible.

> I have 128 on the server. 

128 is the vanilla default entity view distance, so for 99% of people this wont be an issue anyway that you can't crank it to 200+

**Comment by andreasdc** [comment]
Shouldn't all riders be invisible?
Yes but if distance is 128, doesn't that make small space between hide server and 128?

**Comment by tr7zw** [comment]
> Shouldn't all riders be invisible?

why would they?

**Comment by andreasdc** [comment]
To not stay bugged on last position the vehicle was :D

**Comment by tr7zw** [comment]
> 
> 
> To not stay bugged on last position the vehicle was :D

Invisible mobs are still 100% there and updated. Just during render they get skipped.
Now the tick culling with the version I linked above is modified so riding entities never get ticked skipped, at maximum render skipped.

**Comment by andreasdc** [comment]
Yes but when tick culling happens riders stay in the last place vehicle was, the best thing would be to hide them and show when vehicle is visible.

**Comment by tr7zw** [comment]
> 
> 
> Yes but when tick culling happens riders stay in the last place vehicle was, the best thing would be to hide them and show when vehicle is visible.

Thats why tick culling for riders doesn't happen anymore with that build. So they wont get stuck behind in the air.

**Comment by andreasdc** [comment]
Exactly, but they should be also hidden along with the vehicle

**Comment by tr7zw** [comment]
> 
> 
> Exactly, but they should be also hidden along with the vehicle

No, each of them should be checked on their own^^

**Comment by andreasdc** [comment]
How checked?

**Comment by andreasdc** [comment]
I guess you don't want rider to be stuck and bugged in the air where vehicle was last seen

**Comment by tr7zw** [comment]
Just try the latest build, you'll see^^

**Comment by andreasdc** [comment]
All right

**Comment by andreasdc** [comment]
Yes I checked, you don't hide riders

**Comment by tr7zw** [comment]
Why wouldn't they be hidden^^?

**Comment by andreasdc** [comment]
They should be hidden

**Comment by tr7zw** [comment]
Honestly, join the discord and show me there what the heck you mean^^

**Comment by andreasdc** [comment]
give me link bro

**Comment by tr7zw** [comment]
https://discord.gg/fWtMAkFaZF
