### ISSUE TITLE
Minecarts Culling incorrectly (Visual Bug)

### ISSUE THREAD

**Issue by Nicolas-GE** [tr7zw/EntityCulling#34]
when minecarts in a loop (like a supersmelter) go off-screen, they never reappear when they should be coming back in view, this is only a visual bug.

Steps to reproduce:
1. create a minecart loop that can go off-screen
2. look at only half the loop, or at least enough so that the minecart can go off-screen
3. the minecart will not come back in the visible part of the loop, even though it should

mod version: `EntityCulling-Fabric-1.3.2`

**Comment by tr7zw** [comment]
Hm then they also have some custom logic like living entities, but apparently not like itemstacks. Thanks, Minecraft. I'll fix that next release, for now you can add minecarts to the tick culling whitelist in the config file.
