### ISSUE TITLE
Minor issue with Furnace Minecarts

### ISSUE THREAD

**Issue by YumatanGames** [tr7zw/EntityCulling#36]
I've noticed an issue with furnaces minecart... They don't render when they get outside your line of sight. So if you are being pushed by them, they will eventually become invisible, until you look back at the exactly the same place they were before disappearing. To show the problem, I [uploaded a video showcasing it](https://www.youtube.com/watch?v=ytCSS1zt7aE)

The biggest issue with this bug is that if I don't know where were the last point where I saw the furnace minecart, it will remain invisible, somewhere in the rail line. So, it could be a very problematic issue in long rail lines, specially if the user is trying to transport a great number of villagers, for example.

**Comment by tr7zw** [comment]
Did you use the latest version, minecarts should be fully exempt from the tick culling.

**Comment by YumatanGames** [comment]
Yep. My mistake, sorry. I was playing with 1.3.2. I'll test the newer version to see if the problem persist. Sorry about that. :)

**Comment by YumatanGames** [comment]
Yeah. I've tested it with the new version and the problem is gone. Sorry about that.
