### ISSUE TITLE
Double chests culled wrongly

### ISSUE THREAD

**Issue by RaphiMC** [tr7zw/EntityCulling#4]
Double chests are only rendered if the first chest is rendered. So if there are two chests and you only see the second half of the double chests both are not rendered.
Screenshot shows that the whole chest is not rendered even tho one half being visible to the player (Blue boxes are here to visualise where chests would be rendered)
![image](https://user-images.githubusercontent.com/50594595/108716992-0e56c100-751d-11eb-9017-72a10b6d416c.png)

**Comment by tr7zw** [comment]
They render as 2 separated tiles(at least in vanilla). Could this be Sodium or another mod optimizing it to render the doublechest in one pass?
![grafik](https://user-images.githubusercontent.com/5133936/108900338-cb2e4800-7619-11eb-83f9-d4c044f422f2.png)
(Using debug mode which binds the tracing to the player head instead of the camera)

**Comment by tr7zw** [comment]
Ok, it is not Sodium or Lithium doing that. What other mods do you use(especially the chest esp?)
![grafik](https://user-images.githubusercontent.com/5133936/108902754-cae37c00-761c-11eb-9212-73477c7583c7.png)

**Comment by RaphiMC** [comment]
I use optifabric, maybe it renders chests differently. The chest esp is my own mod which doesn't modify the chest rendering. Worth to note is that I backported your mod to 1.14.4 which might by the cause (unlikely). Nevertheless I will try to reproduce my issue on a clean 1.16 fabric with optifabric installed

**Comment by tr7zw** [comment]
So far I haven't seen this with optifabric either. So yea might be some issue with the backport, not sure.

**Comment by RaphiMC** [comment]
Issue is related to my backport. Chest rendering changed over versions and 1.14.4 renders them differently
