### ISSUE TITLE
Put releases on GitHub

### ISSUE THREAD

**Issue by NatoBoram** [tr7zw/EntityCulling#42]
It would be nice if binaries were also distributed via GitHub Releases.

**Comment by tr7zw** [comment]
I think for that I'll look into how to use actions during tags to automate that. Creating releases manually is a bit anoying.

**Comment by tr7zw** [comment]
During testing my isp died, but it seems to work now. So creating a tag on a commit now auto-creates a release and adds the artifacts to the tag. I'll migrate that later to my other projects.
