### ISSUE TITLE
Culling breaks Botania mana burst rendering

### ISSUE THREAD

**Issue by Hubry** [tr7zw/EntityCulling#50]
Mana bursts are spawned inside mana spreaders, which makes them get instantly culled. Because they get culled, they no longer move on the client side, which makes them invisible to the client. (The bursts render purely through particles spawned on the clientside)

The entity id is `botania:mana_burst`, if you want to whitelist them by default.

**Comment by tr7zw** [comment]
Whitelisting the entity did fix it. Not sure how the mana burst is implemented to fail like this otherwise.
