### ISSUE TITLE
[1.16.5-1.18] RenderBoundingBox of BlockEntity is ignored for culling

### ISSUE THREAD

**Issue by TimeConqueror** [tr7zw/EntityCulling#51]
Right now EntityCulling considers the render bounding box of any BlockEntity as a single block with AABB(0;0;0->1;1;1). [click](https://github.com/tr7zw/EntityCulling/blob/b29646e3b34ed87da6ca3e3e574056250dd07363/src/main/java/dev/tr7zw/entityculling/CullTask.java#L84)

This breaks the compatibility with some mods with blockentities which are rendered as multiblocks (where the one renders others).
I have a mod called LootGames, which has the Minesweeper Minigame. The master block of this game which renders the whole game board is hidden in the corner under the walls. It has an infinite AABB for rendering purpose [[click](https://github.com/TimeConqueror/LootGames/blob/ae4348c0c0604e6637b8541b6975117d63574002/src/main/java/ru/timeconqueror/lootgames/api/block/tile/BoardGameMasterTile.java#L56)], so it needs to be rendered wherever the player is. <br>
![image](https://user-images.githubusercontent.com/25156941/146097165-bc6af896-83f0-42d6-9daf-0e141e2d36f7.png)

**Comment by tr7zw** [comment]
It's been a while since I worked on the mc side of the code, but I think I just either didn't know or overlooked that BlockEntities do have a render bounding box too. Will look into fixing this.

**Comment by tr7zw** [comment]
https://github.com/MinecraftForge/MinecraftForge/blob/75408c1a705dd51a5879b2612df310389bfe0143/src/main/java/net/minecraftforge/common/extensions/IForgeBlockEntity.java#L121
This method is native to Forge, not to Minecraft. I'll add it to the forge side of things.
