### ISSUE TITLE
Culling conflict with Supplementaries' notice board

### ISSUE THREAD

**Issue by ghost** [tr7zw/EntityCulling#52]
Heyo! I've found a conflict with this mod and Supplementaries, most likely caused by the culling from this mod. First to explain what the notice board does: You can place in a map to show it as if it was a painting on the wall of the block (hopefully that explains it properly). I'm guessing that the culling misses where the notice boards display entity is and derenders it.

**The issue:** Essentially it does not show when looking at it straight on and you must look around the side of the notice board blocks to see them properly. I've let the Supplementaries mod author know so both of you are informed of the conflict in case you wish to look into it.

**Pictures without the Entity Culling mod (don't mind the maps not lining up, I just used three variants and one of them isn't fully explored):**
![2021-12-14_19 00 05](https://user-images.githubusercontent.com/96159041/146130988-5a034a96-f7d5-40b3-8844-0216f9f6b6ae.png)
![2021-12-14_19 00 01](https://user-images.githubusercontent.com/96159041/146130983-16d31181-b821-4c86-b54a-0189a60120d1.png)

**Pictures with the Entity Culling mod:**
![2021-12-14_19 05 24](https://user-images.githubusercontent.com/96159041/146130989-d108d4d7-153c-448e-98e0-834df9a15040.png)
![2021-12-14_19 05 28](https://user-images.githubusercontent.com/96159041/146130991-e0084515-47a9-4663-b4ed-45495e6fb6f6.png)

**Comment by tr7zw** [comment]
Why closed? The board probably needs to be added to the default ignore list.
