### ISSUE TITLE
[Forge] "Performant" incompatibility

### ISSUE THREAD

**Issue by Atlantispy** [tr7zw/EntityCulling#53]
Running 1.18 forge server with a few mods, some of which may be interacting with to cause the issue.

Mod list:

- AI Improvements
- Amplified Nether
- Clumps
- Dynmap
- Dynview
- Ferritecore
- Get it together drops
- Lazydfu
- Limited chunks
- Performant
- Starlight
- Terralith
- World Pre Generator

On the client side I tested just launching with just Entityculling.

This only recently started happening, and this will have been since adding these mods to the server list:

- Dynview
- Get it together drops
- Limited Chunks
- Performant

The bug is that lots of entities were not being rendered as they came back into view, item frames being the most noticeable, but also noticing piglins being unrendered. If I logged in the room with the item frames they would be there, just not any that I didn't have in view when logging in.

Thanks

**Comment by Atlantispy** [comment]
I've narrowed it down to Performant being the conflict. Have also told the author of said mod.

**Comment by tr7zw** [comment]
I never used/heard of Performant, so I'll look into it at a later point when I'm done with my uni projects and back to modding.

**Comment by tr7zw** [comment]
Ok looking at the mod page, I guess there is some logic conflict that causes the entity to fail to get unculled. Also for a sanity check, you have Performant installed on the client too?

**Comment by Atlantispy** [comment]
> Ok looking at the mod page, I guess there is some logic conflict that causes the entity to fail to get unculled. Also for a sanity check, you have Performant installed on the client too?

Yes, installed on both. I've been told performant breaks a lot by some other modders, so I don't know if it's worth your time. The author of performant said it has entity culling built into it, but I don't believe it's *as* thorough as this. It's closed source so many people don't worry about the compatibilities with it, but maybe could mark it as incompatible in dependencies.

**Comment by tr7zw** [comment]
Oh yea, if it's closed source that will make it quite a bit harder. I think just installing it on the server to do AI optimizations etc. and then optimizing the client using ~~Sodium, EntityCulling, Lithium, Starlight, Enhanced Block Entities~~(ah crap this is Forge, so no luck there)

**Comment by Atlantispy** [comment]
> Oh yea, if it's closed source that will make it quite a bit harder. I think just installing it on the server to do AI optimizations etc. and then optimizing the client using ~Sodium, EntityCulling, Lithium, Starlight, Enhanced Block Entities~(ah crap this is Forge, so no luck there)

I've ended up just using other mods honestly. There's plenty of replacements. I'd consider it closed and just mark incompatible!

**Comment by someaddons** [comment]
Fixed it on performants side, it'll disable its own culling when this mod is additionally installed for that, as there is no reason to do it twice then.

**Comment by tr7zw** [comment]
Ok cool, then I'll close this issue.
