### ISSUE TITLE
[Suggestion] Implement ExtensionPoint.DISPLAYTEST

### ISSUE THREAD

**Issue by jeremiahwinsley** [tr7zw/EntityCulling#58]
Currently, the mod is required on both client and server or Forge will mark the connection as incompatible (and mod doesn't work on servers).

Forge allows registering an extension point to bypass this check, for mods that don't require both sides to be present.

See the docs here for 1.16.x: https://mcforge.readthedocs.io/en/1.16.x/concepts/sides/#writing-one-sided-mods

and here for 1.18.x syntax: https://mcforge.readthedocs.io/en/1.18.x/concepts/sides/#writing-one-sided-mods

**Comment by tr7zw** [comment]
https://github.com/tr7zw/EntityCulling/blob/1.17/EntityCulling-Forge/src/main/java/dev/tr7zw/entityculling/EntityCullingMod.java#L46
https://github.com/tr7zw/EntityCulling/blob/1.18/EntityCulling-Forge/src/main/java/dev/tr7zw/entityculling/EntityCullingMod.java#L46
https://github.com/tr7zw/EntityCulling/blob/1.16-backport/EntityCulling-Forge/src/main/java/dev/tr7zw/entityculling/EntityCullingMod.java#L47

Should be part of 1.16-1.18?

**Comment by jeremiahwinsley** [comment]
Sorry, my mistake. I didn't notice Curseforge was installing the latest stable release (1.0.2), not the latest beta (1.4.0). After updating to the beta, it works as expected. Thanks!

**Comment by tr7zw** [comment]
Technically they are not beta, the forge builds are just marked as such so they both show up on the main page. Usually the CurseForge launcher should also be downloading the beta versions if they are more recent 🤔. I'll look for that 1.0.2 build and mark it as a beta too, so it can't take priority.
