### ISSUE TITLE
Is 1.4.0 officially released?

### ISSUE THREAD

**Issue by iammattcoleman** [tr7zw/EntityCulling#60]
CurseForge is showing 1.4.0 as the latest version, but it hasn't been tagged in git yet. Is it still being tested (and CurseForge jumped the gun) or has it been released?

**Comment by tr7zw** [comment]
It is released, I just lack behind a bit with tagging everything, since I released like 9 updates over 2 days with tons of different branches.

**Comment by iammattcoleman** [comment]
Thank you for the explanation.

...and thanks for making such a great mod. This is absolutely needed to make the game playable on my system!

**Comment by tr7zw** [comment]
Finally managed to catch #39 , so 1.5.0 is out now, and this time I've tagged all of them.
