### ISSUE TITLE
Fabric 1.16.5 doesn't run using Java 8

### ISSUE THREAD

**Issue by Lartza** [tr7zw/EntityCulling#61]
Starting with 1.4.0 and continuing to 1.5.0 the Fabric 1.16.5 version refuses to run on Java 8 and only accepts Java 16+

latest.log
https://gist.github.com/Lartza/91d50cc0e7233336a3bf8e5f6610a17d

**Comment by tr7zw** [comment]
> has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0

https://github.com/tr7zw/EntityCulling/blob/1.16/.github/workflows/build.yml#L15

Hmmmmmmmmmmmmmmm well guess I overlooked that when doing the backport, since I run everything in Java 17. Will do a patch for that.
