### ISSUE TITLE
Null pointer on entity render (1.16.5)

### ISSUE THREAD

**Issue by pokermanx** [tr7zw/EntityCulling#64]
I got this twice, with Aquaculture and Thermal now, Both astral and twillight had no issues with existing together with others.
Thermal: https://pastebin.com/6VXHbxu6
Aquaculture https://pastebin.com/XPaNUu50

**Comment by tr7zw** [comment]
The Thermal one doesn't seem to have anything to do with EntityCulling? It's a thermal:basalz entity trying to render, getting a NPE in the LivingRenderer.render. Same with the Aquaculture crash. EntityCulling has no mixins in that place and doesn't null anything out. Only other clue from the stacktrace seems to be that "charm" has applied mixins there.

**Comment by pokermanx** [comment]
wrong repo
