### ISSUE TITLE
Issue with rendering player names on sodium

### ISSUE THREAD

**Issue by backslashspace** [tr7zw/EntityCulling#67]
On servers with a custom name tag plugin which use armor stands on the head of players in combination with sodium causes the name tag behind walls to disappear / flicker.

(it's independent of the sodium setting for entity culling)

https://cdn.discordapp.com/attachments/864480483227598858/963085564087783555/2022-04-11_16-34-20.mp4

modversion 1.5.1 (fabric)

**Comment by tr7zw** [comment]
Hm also seems to happen with 1.5.0. I'll look into it.

**Comment by tr7zw** [comment]
Wait no that was Cubecraft doing some weird shit in their lobby. Really stupid question: could it be that the person just sneaked xD?

**Comment by backslashspace** [comment]
i tested it with my alt after i noticed it

(he wasnt sneaking no)
i was also using iris, lithium and startlight if thats important

i tested on fighttosurvive.net (was fine in signle player)

**Comment by tr7zw** [comment]
I'm using the same mods, so no clue. Will keep an eye out for it, since I need a reproducible setup to debug it.

**Comment by backslashspace** [comment]
maybe this helps in any way
https://cdn.discordapp.com/attachments/864480483227598858/963153214524493884/2022-04-11_21-04-39.mp4

**Comment by backslashspace** [comment]
https://cdn.discordapp.com/attachments/864480483227598858/966296450831102022/2022-04-20-13-01-56.mp4

as seen here, it even happens when observing entities more directly

**Comment by tr7zw** [comment]
Can I get a modlist? Since so far no one else reports this, it is rather odd.

**Comment by backslashspace** [comment]
![Screenshot 2022-04-20 170916](https://user-images.githubusercontent.com/86926768/164263277-44706a32-5fb6-4c45-b0a5-5b2cdb2e7718.png)

**Comment by tr7zw** [comment]
This issue has been quiet for 2 years, closing.
