### ISSUE TITLE
Entity Culling not working anymore on 1.18.2

### ISSUE THREAD

**Issue by livelyeko** [tr7zw/EntityCulling#69]
On 1.18, the mod was working spectacularly: the apartment I built with many decoration blocks and entities was handled well and my fps was well above 30.

However, on 1.18.2, whenever I look at the build from the outside, the fps drop to 20 and below despite the rooms being covered by the wall. 

Here's a video showing this in 1.18.2: https://drive.google.com/file/d/17YLnB2M2rU0zg5-dMy0gES9u4f-n-b6o/view?usp=sharing

I apologize if this isn't a proper way to create an issue thread. I'm kind of new here, but if I need to do anything please tell me.

**Comment by livelyeko** [comment]
Mods I have:
Sodium
Lithium
Phosphor
BSVSB (Better Sodium Video Settings Button)
Iris
WI-Zoom   <- upon second thought, this may be the reason. It's a zoom mod but it may have done something to the camera?
WorldEdit Mod
Xaeros_Minimap
Xaeros_WorldMap

**Comment by livelyeko** [comment]
Update:

It's the WI-Zoom. I deleted it from the files and the entities are now being skipped properly. I'll keep this thread up so the owner can see it and maybe add it on the blacklist lol. Now I'll have to find another zoom mod.

**Comment by tr7zw** [comment]
Looking at WI-Zoom there is nothing in there that should be able to cause this. Did you maybe accidentally toggle the culling via the hotkey/config?

**Comment by tr7zw** [comment]
The culling thread could also have crashed, and I know that an older version for 1.18 had a bug that it didn't work correctly at all on forge(and for some reason on fabric, but it shouldn't have?). So also check that you are on the latest version.

**Comment by livelyeko** [comment]
I don't have a hotkey set for the culling, so I don't think that was the problem (I didn't even know there was a hotkey, which is great).

I think I actually used the most recent file for the culling mod since it's only been three days since my first download. I just used them both for opening up the 1.18 and 1.18.2 versions of Minecraft. I thought there was something with the 1.18.2 version, but upon removing WI-Zoom mod the culling worked perfectly fine. It may just be a coincidence though.

**Comment by tr7zw** [comment]
Keep an eye open for it, when it happens again please send the latest.log. My guess would be that the culling thread got stuck on something, or some mixin going wrong.

**Comment by livelyeko** [comment]
Will do. I'll be able to notice it right away since the build I'm creating has so many entities. Thanks.

**Comment by livelyeko** [comment]
I'll actually test the WI-Zoom mod one more time just to be sure.

**Comment by livelyeko** [comment]
Oh, boy was I seriously wrong. It's not the WI-Zoom mod after all smh

I put the mod back in the folder, and lo and behold it's working fine. Looks like the culling thread did crash at the same time when I downloaded the mod. What timing.
