### ISSUE TITLE
Mod has issues with mobs with bigger hitboxes

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [tr7zw/EntityCulling#7]
Mod has issues with mobs with bigger hitboxes, i.e. withers. See video before. I use quite a few mods, but it's likely this one. I am testing with the master branch, latest commit as of now (f0ed8d5).

https://gph.is/g/EvWjKXg

**Comment by tr7zw** [comment]
Test with the other branch, there it should be fixed already.

**Comment by DragonEggBedrockBreaking** [comment]
> Test with the other branch, there it should be fixed already.

Cannot reproduce on the other branch. Should I close this now, or will you do so when it is branched into master?

**Comment by tr7zw** [comment]
Guess can be closed since it will be on curse in a few days.
