### ISSUE TITLE
[Curseforge] Allow usage of curseforge api

### ISSUE THREAD

**Issue by Merith-TK** [tr7zw/EntityCulling#70]
![image](https://user-images.githubusercontent.com/10422110/170145322-1ad4bf51-e31a-4dcb-a962-c068610b7b9c.png)

basically the latest curseforge api update means that your mod has to have this checked otherwise only manual downloads/curseforge launcher are capable of downloading it

I use this mod in my Vanilla+ modpack and would love for it to be able to be used again

**Comment by tr7zw** [comment]
Because Curseforges api turned out to be such a mess, I'll upload EntityCulling later to Modrinth later today (#30) anyway. CurseForge modpacks = CurseLauncher, any other modpacks = other launchers = modrinth.

**Comment by tr7zw** [comment]
https://modrinth.com/mod/entityculling is the url as soon as it's approved/processed.
