### ISSUE TITLE
Unclear Licensing

### ISSUE THREAD

**Issue by Scrumplex** [tr7zw/EntityCulling#71]
I was looking at the licensing of this project, and I am unsure what to follow.

https://github.com/tr7zw/EntityCulling/blob/1.18/LICENSE-EntityCulling says that I can distribute this software as long as I don't use it to get a commercial advantage or monetary compensation.

But looking at the README instead reveals that I am not allowed to distribute this at all, even if I created a derivative work.

This means I would already break the license, when forking the project, as GitHub Actions will automatically run and create a binary that will be distributed by GitHub.

So what really applies here?

**Comment by LennyMcLennington** [comment]
https://github.com/tr7zw/EntityCulling/blob/1.18/LICENSE-EntityCulling doesn't even mention the word distribute. Copyright is all rights reserved by default, and you haven't been granted the right to distribute.

**Comment by tr7zw** [comment]
> doesn't even mention the word distribute. Copyright is all rights reserved by default, and you haven't been granted the right to distribute.

That's precisely the point. The license doesn't grant the right to redistribute(All rights reserved)

> [LICENSE-EntityCulling](https://github.com/tr7zw/EntityCulling/blob/1.18/LICENSE-EntityCulling) says that I can distribute this software as long as I don't use it to get a commercial advantage or monetary compensation.

No, it says you can not use it to gain a commercial advantage or monetary compensation. (This is more of a catch-all against [certain](https://www.lunarclient.com/news/patch-notes-17/) for-profit Clients so they don't get funny ideas like downloading the source from Github and compiling it on the go)

> But looking at the README instead reveals that I am not allowed to distribute this at all, even if I created a derivative work.

Correct. You can create and use your own derivative works or create pr's, but not share prebuilt versions.

> This means I would already break the license, when forking the project, as GitHub Actions will automatically run and create a binary that will be distributed by GitHub.

Don't think the Github actions autorun on forks? But this falls under https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#3-ownership-of-content-right-to-post-and-license-grants= anyway, so it should be fine too. Actions files are temporary, and as long as you don't create a fork with tags that contain files and then start auto-downloading them in a launcher, it's all fine.

See the license either as a: A cutdown version of MIT without the redistribution parts or as All rights reserved with the added rights to modify and compile the source and use the result.

**Comment by tr7zw** [comment]
In case you are trying to do something specific where the license might become an issue feel free to message me on discord.
