### ISSUE TITLE
Licence issue

### ISSUE THREAD

**Issue by UntalentedAmateur** [tr7zw/EntityCulling#72]
The way you have described the authorised distribution for EntityCulling in your Readme.md seems to now be broken with your mod being uploaded (by you) onto Modrinth.  With the explanatory text in your licencing, it seems that we can not legitimately download and use the mod from Modrinth (or build from source here on Github - both places where you have uploaded the content).

Can you please revise the licence so that it is a little clearer about being able to download (and include in modpacks) from sites where you have uploaded it?

**Comment by tr7zw** [comment]
The license is ARR(All Rights reserved) with more rights or alternatively MIT but with the redistribution rights removed. Nothing in there stops you from downloading it from Modrinth. The part in the readme is just to clarify that other terms of service interact with it(Be it Github allowing forks, CurseForge modpacks, or Modrinth downloads). In the case of Modrinth, that's https://modrinth.com/legal/terms . Also yes you can build it from the source here from Github, the license explicitly allows that.

**Comment by tr7zw** [comment]
> Can you please revise the licence so that it is a little clearer about being able to download (and include in modpacks) from sites where you have uploaded it?

You can always download mods from Modrinth/curseforge, that's in their TOS. You can always clone code from Github, that's their TOS. The only restriction on usage from the license is to now allow commercial Modpacks/Clients(in that case contact me first, then I can give an approval). You can thank the Lunar client for just copy pasting my mods, that's the reason it's no longer simple open-source(MIT).

**Comment by UntalentedAmateur** [comment]
Hi tr7zw,

Thanks for the clarification.  Seeing it as MIT with redistribution removed makes a lot more sense.  I'm working my way through my mods at the moment and checking their licences to see how to manage them.  I got your mod through Modrinth, but the wording and explanation text didn't make a lot of sense and I wasn't sure how it applied.

Great mod, btw!

**Comment by Secret-chest** [comment]
@tr7zw Please use the GPLv3 with Minecraft linking exception. I can explain:
* The licence allows redistribution and commercial use.
* However, ALL redistributed, modified or not, copies must use the same licence and be open source.
* Additionally, the licence forbids any software from integrating this software unless it uses GPLv3 as well.
* However, the Minecraft linking exception allows usage with Minecraft, even if it isn't open-source.

So, it would:
* Allow permissive usage for _normal_ users.
* Forbid clients from using it since clients are never open-source.

Additionally, the current licence is a bit unclear. Do you intend to completely ban commercial use? The licence currently reads that we cannot use the mod for _any_ commercial use, including using it in YouTube videos with monetisation.

**Comment by tr7zw** [comment]
The current license is basically ARR with some added freedoms. No, it doesn't prevent the usage in YouTube videos, otherwise you couldn't use any ARR mods or no-commercial licenced mods for videos. If I were to revisit the topic of licence again, I'd probably just use ARR and call it a day.

**Comment by Secret-chest** [comment]
Please do use ARR if you want to look open source, but in reality grant no freedoms.

**Comment by tr7zw** [comment]
Never said these mods are open source? The current license isn't open source by definition.

**Comment by Secret-chest** [comment]
Well they technically are, this looks a bit misleading.

**Comment by Secret-chest** [comment]
I'm not using it in my optimisation modpack because I want the freedom to distribute it even where your mods are not posted.

**Comment by Secret-chest** [comment]
But I don't want to hurt you. Go ahead and keep making fake open-source mods in which I have no trust.

**Comment by tr7zw** [comment]
> Well they technically are, this looks a bit misleading.

They are not. The license doesn't allow anyone to redistribute the mods.

**Comment by Secret-chest** [comment]
Just so I tell you why this strategy is bad before I leave. Many Bukkit plugins (especially) have survived because someone took over. With nonfree software this is not possible.

Open source means visible source. Your mods are open source but not free software. That's my problem

**Comment by Secret-chest** [comment]
Right now this is not a problem, but do make sure to use real free software licences when you want someone to depend on your mods and trust you.

**Comment by tr7zw** [comment]
I know about this, especially in the bukkit space, I have been around hmod/spigot etc for over 10 years. When I stop doing mc stuff, I will make everything open source. But right I would just harm myself by doing that.

Also no, open source does in fact not mean visible source. You should look up what open source means. Code being on github does not mean something is open source.
