### ISSUE TITLE
Incompability with DynamicFPS?

### ISSUE THREAD

**Issue by andreasdc** [tr7zw/EntityCulling#73]
Incompability with DynamicFPS? After some time my cpu is at 20% not 4% when minimalized. https://github.com/juliand665/Dynamic-FPS/issues/59
Lagged: 
![image](https://user-images.githubusercontent.com/82218780/172655164-61ddb877-40aa-41a0-ab54-9413f11c76ad.png)
Normal:
![image](https://user-images.githubusercontent.com/82218780/172655204-bec6606c-c5de-4e43-9379-f8b4d0621535.png)

**Comment by juliand665** [comment]
Funky! If you can, maybe try without Dynamic FPS and see if it still happens?

**Comment by andreasdc** [comment]
> Funky! If you can, maybe try without Dynamic FPS and see if it still happens?

How can it happen without Dynamic FPS?

**Comment by tr7zw** [comment]
Well I can tell you that the cullthread won't care about being in the background/DynamicFPS doing anything (it's a separate thread just in a while loop with a sleep). Can you send the lagged spark timings?

**Comment by andreasdc** [comment]
> Well I can tell you that the cullthread won't care about being in the background/DynamicFPS doing anything (it's a separate thread just in a while loop with a sleep). Can you send the lagged spark timings?

In the lagged profile there is no sleeping if i'm not wrong.

**Comment by tr7zw** [comment]
I need the full thing. 36% on hasNext sounds like something going wrong with mc?

**Comment by tr7zw** [comment]
I'm pretty sure that spark screwed up the profiling there(it's missing a ton of info and the info that is there is wrong), the two mods work perfectly well together, and whatever causes the CPU usage to not lower correctly is not related to EntityCulling.

**Comment by andreasdc** [comment]
> I'm pretty sure that spark screwed up the profiling there(it's missing a ton of info and the info that is there is wrong), the two mods work perfectly well together, and whatever causes the CPU usage to not lower correctly is not related to EntityCulling.

What is causing it then? You have 2 profilers.

**Comment by tr7zw** [comment]
I can't tell you that, since spark can't tell you cpu usage based on threads. (and the fact that the profiling like I said is broken)

**Comment by juliand665** [comment]
Hm, is it possible it's Spark itself that's getting messed up by Dynamic FPS's backgrounding stuff? Though generally it should only affect the rendering thread, parking it for a short time so as to avoid a busy loop.

**Comment by andreasdc** [comment]
> Hm, is it possible it's Spark itself that's getting messed up by Dynamic FPS's backgrounding stuff? Though generally it should only affect the rendering thread, parking it for a short time so as to avoid a busy loop.

99% chance that it's not spark's fault, only thing that is different from the normal profile is CullThread's behaviour, probably stuck at the loop and not going to sleep.

**Comment by andreasdc** [comment]
Also my guess is that something bad happens near that line and it gets stuck on the loop.
![image](https://user-images.githubusercontent.com/82218780/172959029-36d4517e-28a8-4d82-8545-ce07e2e6348e.png)

**Comment by tr7zw** [comment]
> Also my guess is that something bad happens near that line and it gets stuck on the loop.
> ![image](https://user-images.githubusercontent.com/82218780/172959029-36d4517e-28a8-4d82-8545-ce07e2e6348e.png)

That's block entities, they don't even use the Google iterator. Like I said, the timings are garbo.
