### ISSUE TITLE
[1.12] Massive Lag when near vanilla chest

### ISSUE THREAD

**Issue by Krutoy242** [tr7zw/EntityCulling#74]
Coming closer to vanilla Chest cause massive lag (FPS drop to 2).

<img src="https://i.imgur.com/mpJ0uKk.png" width=400/>

### Video: https://streamable.com/conluh

This also happen with Rustic's Cabinets and Dark Oak Chests

<img src="https://i.imgur.com/SlMT6AM.png" width=200/>

Removing EntityCulling fixes this issue.
This issue reported only by 1 player of `E2E-E` [![Curse Forge](https://cf.way2muchnoise.eu/full_561105_downloads.svg)](https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended) modpack, so seems like it very rare.

**Versions**:
`RenderLib-1.12.2-1.0.8`
`EntityCulling-1.12.2-6.0.2`
`Forge 14.23.5.2860`

**Comment by tr7zw** [comment]
Ehhhh ``EntityCulling-1.12.2-6.0.2`` there is no 1.12 version of EntityCulling(this mod)(also note to self, port the 1.8 version to 1.12). I guess this is https://www.curseforge.com/minecraft/mc-mods/entity-culling ? https://github.com/Meldexun/EntityCulling

**Comment by Krutoy242** [comment]
Oooops, probably i found wrong `EntityCulling`, sorry 😅
