### ISSUE TITLE
1.19 Latest Forge Crash

### ISSUE THREAD

**Issue by MianReplicate** [tr7zw/EntityCulling#75]
Currently EntityCulling (Forge) crashes on the latest versions of Forge upon startup.

Minecraft Version: 1.19
Forge Version: 41.0.85
Mod Version: 1.5.1

Crash report
https://mclo.gs/xu9XMdB

**Comment by tr7zw** [comment]
Looks like forge broke something. Potentially downgrade to an older version(of forge).

**Comment by MianReplicate** [comment]
I'll just wait for the mod to be fixed so I can update to the newer versions of forge. My other mods have already updated, waiting for this one and a few others now before I push my modpack update to the stable branch.

Hope you can get it fixed soon! :)

**Comment by tr7zw** [comment]
Why does Forge break API in the first place 😒. I'll look into it when I have time, but people really should stop using Forge in general.

**Comment by MianReplicate** [comment]
Ikr, it's so annoying I wish Forge didn't do stuff like this. I'd stop using Forge honestly but without my other mods updating to Fabric I can't switch to Fabric.

Alex's Mobs, Ice and Fire, and Tinkers Construct are just some of the few mods that prevent me from switching.

So I play both Fabric and Forge to solve this issue.

**Comment by tr7zw** [comment]
Fyi for the future on this issue: Gonna follow other mod devs and not update Forge 1.19 till they are done with whatever the heck they are doing.

**Comment by mont-40** [comment]
In the Forge changelogs there's a line at 41.0.64 that mentions "Remove ClientRegistry, as everything has been moved out of it". It's quite annoying they make API breaking changes in minor or patch versions, unfortunately it has become a common theme in Forge development. They should stick to proper [semantic versioning](https://semver.org/).
