### ISSUE TITLE
Add Train entities (Create 0.5) to whitelist

### ISSUE THREAD

**Issue by ClaytonAstrom** [tr7zw/EntityCulling#76]
Cross posting Creators-of-Create/Create#3195

Trains in Create 0.5 are invisible when they are created if Entity Culling is present.

**Comment by tr7zw** [comment]
They either need to be added to the whitelist, or Create needs to fix the visual hitbox of the entities(that's probably what's wrong in the first place).

**Comment by tr7zw** [comment]
``create:carriage_contraption``

**Comment by tr7zw** [comment]
Update: the issue causing the invisibility was found in Create, so adding them to the whitelist shouldn't be required.
