### ISSUE TITLE
Culling doesn't work on fast leaves

### ISSUE THREAD

**Issue by AleFunky** [tr7zw/EntityCulling#78]
![imagen](https://user-images.githubusercontent.com/55950650/179972748-190874b0-202b-42ba-86de-d675fc7ad68e.png)
there is like 500 sheeps behind the tree and it says 397 rendered entities

**Comment by tr7zw** [comment]
Leaves are still transparent blocks from mc's point of view, so culling fully ignores them. Might be able to hack something in for fast graphics.

**Comment by tr7zw** [comment]
After looking into it, adding this special case would add too much overhead on all calls, especially with most people not playing on fast rendering, and leaves usually not being in a position to hide stuff. Will keep the current behavior.
