### ISSUE TITLE
This mod doesn't respect entity distance

### ISSUE THREAD

**Issue by CalXee** [tr7zw/EntityCulling#8]
Any entity outside of the listed 128 block range is unrendered and considered too far away, even when turning up entity distance. As a result, it renders the entity distance option useless.

Without EntityCulling, entity distance 500%
![2021-03-09_14 05 29](https://user-images.githubusercontent.com/68349758/110685569-6d1e6a80-81ac-11eb-847d-567c389cd188.png)

With EntityCulling, entity distance 500%
![2021-03-09_14 07 04](https://user-images.githubusercontent.com/68349758/110685605-77406900-81ac-11eb-8e72-87e55ca875ec.png)

**Comment by xpopy** [comment]
This is mentioned on the curseforged page

> This mod calculates the visibility of tile/-entities 64 blocks in each direction of the player(so a 128x128x128 cube in total), everything outside of that is considered too far away and is invisible

I assume its temporary and will be fixed in the future

**Comment by tr7zw** [comment]
Yea also from the comments:
> id gladly use this if the entity rendering range is ever configurable/increased!
> i enjoy seeing entities from quite a distance away (especially with mods like WI Zoom)

> The issue is that increasing the tracing distance exponentially increases the work/memory needed. Once everything is stable I'll try to make it use the entity view distance sliders value, for now, it is 64 blocks(the maximum distance you can see stuff like chests/signs in vanilla).

**Comment by supersaiyansubtlety** [comment]
In the meantime, would it be possible to just stop entity culling from culling anything when entity render distance is >100%?
This would at least allow us to check on distant entities with the mod installed.

**Comment by tr7zw** [comment]
That branch has (hopefully) a lot of bugfixes and also doubles the max tracing distance to 128. Stuff that is even further will now just be marked as ok to render(if the entity view distance allows it). Would be neat to get feedback, and can be downloaded from https://github.com/tr7zw/EntityCulling-Fabric/actions?query=branch%3Aexternal , the select the newest build, and then "Artifacts" download at the bottom of the page.

**Comment by supersaiyansubtlety** [comment]
This mostly fixes the >build limit issues for me, except the player themselves doesn't render above build limit in third person.

**Comment by tr7zw** [comment]
> 
> 
> This mostly fixes the >build limit issues for me, except the player themselves doesn't render above build limit in third person.

![grafik](https://user-images.githubusercontent.com/5133936/111903168-2d277500-8a41-11eb-89c9-75b43e584528.png)
 ?

**Comment by tr7zw** [comment]
Update: this isn't an issue of the culling mod that the player turns invisible when too high/low. You can test that by toggling the culling off with the hotkey, the player stays invisible. Also, it doesn't happen with just the culling mod installed. My guess is that it's optifine? So won't stop the release because of this since it is unreleated.

**Comment by DragonEggBedrockBreaking** [comment]
> That branch has (hopefully) a lot of bugfixes and also doubles the max tracing distance to 128. Stuff that is even further will now just be marked as ok to render(if the entity view distance allows it). Would be neat to get feedback, and can be downloaded from https://github.com/tr7zw/EntityCulling-Fabric/actions?query=branch%3Aexternal , the select the newest build, and then "Artifacts" download at the bottom of the page.

So has this bug been fixed?

**Comment by tr7zw** [comment]
Yea give it a try with https://github.com/tr7zw/EntityCulling-Fabric/actions/runs/673082579 , currently validating that everything works as it should so I can release it on Curse.

**Comment by supersaiyansubtlety** [comment]
> Update: this isn't an issue of the culling mod that the player turns invisible when too high/low. You can test that by toggling the culling off with the hotkey, the player stays invisible. Also, it doesn't happen with just the culling mod installed. My guess is that it's optifine? So won't stop the release because of this since it is unreleated.

Hm, I don't use optifine so it's not that. Strange.
