### ISSUE TITLE
[1.18.2] Culling not working on Create blocks

### ISSUE THREAD

**Issue by Ainsley4Ever** [tr7zw/EntityCulling#80]
Not sure in this is intended or not, or maybe I'm doing something wrong, but all the blocks from the Create mod, from cogs to shafts to rails, don't seem to be culled. Because of this, all the players on our server experience major FPS drops when near large machines, even if they're underground.

**Comment by tr7zw** [comment]
Too big machines will not be culled, because the culling would require too much time. Otherwise, issues with create should have been fixed inside create.
