### ISSUE TITLE
[Forge 1.19.1] Living entities won't get hidden.

### ISSUE THREAD

**Issue by WestPrime** [tr7zw/EntityCulling#81]
I have a big cow and sheep farm, there is a lot of them. They are under the ground, however if I look at them through grass blocks, fps instantly drops to 30. (Optifine + Complementary shaders go fine in 60 FPS VSync)

**Comment by tr7zw** [comment]
Shaders might still be impacted, or it might be too close to the wall. I don't test with Optifine shaders(I play with Sodium+Iris), so maybe Optifines shaders just react differently in that case.

**Comment by tr7zw** [comment]
Closing as stale.
