### ISSUE TITLE
1.18.2 Create 0.5.0c Train

### ISSUE THREAD

**Issue by OfficialPixelBrush** [tr7zw/EntityCulling#84]
Different parts of the train get culled, resulting in different parts of it getting stretched all around, making the train incredibly confusing to use.

**Comment by ITCMD** [comment]
Can confirm. Adding to whitelist will likely help but I can't identify what it is called. Any tips?

**Comment by OfficialPixelBrush** [comment]
Right. Just knowing what the entity is called would be a great help.

**Comment by OfficialPixelBrush** [comment]
> Can confirm. Adding to whitelist will likely help but I can't identify what it is called. Any tips?

I found out what the Blockentity is called, it's `create:carriage_contraption`, apparently.

**Comment by tr7zw** [comment]
Hm I've assumed that Create in its latest versions should work correctly, but apparently not. I can put some more create stuff into the whitelist for the next release.

**Comment by ITCMD** [comment]
Awesome, thanks TR!

In the meantime, at least we can fix it ourselves with that whitelist item!

**Comment by tr7zw** [comment]
I assume this was left open on accident?
