### ISSUE TITLE
Um...little problem 

### ISSUE THREAD

**Issue by Nothinggop** [tr7zw/EntityCulling#85]
Hi, tr7zw,
thank you create a great mod first,
And i got some questions for this,
(By the way , eng not my main language)

Sample:
I build a stone wall 9*3*1 ,
The wall block my view,
I think the mod will be working,
But its not, 
Can't u try it ？

**Comment by tr7zw** [comment]
I can't quite follow. 
> I build a stone wall 931

What does this mean^^?
How do you come to the conclusion that it's not working?

**Comment by Nothinggop** [comment]
傳送自 Yahoo奇摩電子信箱 Android 版 
 
   在 2022 年 9月 月 22 日週四，時間：23:09 ， tr7zw ***@***.***> 寫道：   


I can't quite follow.


I build a stone wall 931


What does this mean^^?
How do you come to the conclusion that it's not working?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.







I send a sample to u ,

After 2 hours

**Comment by Nothinggop** [comment]
https://upload.cc/i1/2022/09/24/yIP7JM.png
https://upload.cc/i1/2022/09/24/lEB9mT.png
https://upload.cc/i1/2022/09/24/2UCpP0.png
https://upload.cc/i1/2022/09/24/JavV0o.png

**Comment by tr7zw** [comment]
Seems to work? (21 fps in the last screen) The first and second screen use stone fences, these are ignored and treated as air.

**Comment by Nothinggop** [comment]
Oh, thank u a  reply,
Got it :)
