### ISSUE TITLE
1.18.2 crash after world load once near bed and trying to click on it

### ISSUE THREAD

**Issue by SDUBZ** [tr7zw/EntityCulling#88]
Minecraft Version
1.18.2

Forge Version
40.1.85

EET:1.18-1.5.1

crash report:
https://gist.github.com/SDUBZ/f0e5cd8296f5deefe16241762f36ea77

logs:

https://github.com/SlimeKnights/TinkersConstruct/files/10093581/debug.log

https://github.com/SlimeKnights/TinkersConstruct/files/10093583/latest.log

**Comment by SDUBZ** [comment]
not sure if you are the one registering things as null but it was mentioned here https://github.com/SlimeKnights/TinkersConstruct/issues/5028

**Comment by tr7zw** [comment]
Uhhh, and what does this have to do with this mod? The crash log is something inside tinkers construct, and the logs basically don't mention anything related to EntityCulling. No to mention that beds are not (block)entities, so the mod doesn't do anything with them.
