### ISSUE TITLE
Ticked entities randomly getting doubled

### ISSUE THREAD

**Issue by sdcard2008** [tr7zw/EntityCulling#89]
Hi , recently for some reason the ticked entities value is getting doubled randomly

https://user-images.githubusercontent.com/100673474/205504208-d49157f4-83c9-480f-bab2-2a3d8e2273fe.mov

**Comment by tr7zw** [comment]
This is caused by mod combinations like with Exordium and potentially mods like Sodium/Optifine/Iris. This is nothing bad, since it's just a visual issue with these debug counters, not anything actually going wrong(for example shaders will also cause entities to be counted multiple times).
