### ISSUE TITLE
Origins Compatibility

### ISSUE THREAD

**Issue by acanthii** [tr7zw/EntityCulling#91]
Hello! This mod really helps me with performance, but I have a bit of an issue when it comes to Origins compatibility!

The Origins mod has a power that lets you see entities through walls via the Glowing potion effect (however, it's applied locally). The problem lies in the fact EntityCulling stops rendering entities that exist through walls.

I think potential solutions could be:
- Adding a config option to blacklist all MOBS from culling, so I can continue to cull blockentities.
- Disabling mob culling when the glowing power is activated

You're able to read more about the power in question here: https://origins.readthedocs.io/en/latest/types/power_types/entity_glow/#entity_glow

**Comment by tr7zw** [comment]
Is that mod open source(on Github), and for which mc version(s) is it?

**Comment by acanthii** [comment]
Github for Origins: https://github.com/apace100/origins-fabric
And it's available for 1.19 / 1.19.2 Fabric! (There is an **unofficial** forge port, but that's up to you to support haha)

Thank you!

**Comment by tr7zw** [comment]
> There is an unofficial forge port, but that's up to you to support haha

You know the deal :D

![](https://images-ext-2.discordapp.net/external/x2G8b1gtQbq1mlH05NbqplyNmPkRpjhkfBtRFKcheBc/https/cammiescorner.dev/images/extras/no_forge.png)

I can look into adding a hook to auto-disable culling while this is going on(like during spectator mode/freecam).

**Comment by acanthii** [comment]
Much appreciated! Only mob culling would need to be disabled, if you're able to just disable that during power activation! (I don't believe the power can make blockentities glow, and as someone who plays with lots of blockentities it'd be much appreciated if it also didn't disable the culling for that lol)

**Comment by tr7zw** [comment]
Will be a bit tricky, since there is currently no logic for that. But should be doable.

**Comment by acanthii** [comment]
Ahh sorry. Saw in the config file that blockEntityWhitelist and entityWhitelist were two seperate categories so I thought there was already logic in place for disabling one or the other ;P

But again much thanks ^^

**Comment by tr7zw** [comment]
Yea these are checked on their own, but internally there is currently just one global on/off toggle, which will have to be split into two(or add a redundant one, that overwrites the other one).
