### ISSUE TITLE
1.16.5 compatible suggestions

### ISSUE THREAD

**Issue by kiahir** [tr7zw/EntityCulling#92]
I hope you can optimize "Ice and Fire: Dragons". Because the dragon can't be seen in the distance.

**Comment by tr7zw** [comment]
Thats probably not an issue with this mod. If they render further away than this mod will cull, then they will just render. You can bind the debug key to test if its this mod. In case it is, add the entities to the whitelist in the config file.

**Comment by tr7zw** [comment]
Closing since inactive and not unrelated to this mod.
