### ISSUE TITLE
Entity rendering mechanism optimization

### ISSUE THREAD

**Issue by 189521394** [tr7zw/EntityCulling#93]
machine translation
I noticed a very serious problem, the entity rendering mechanism, in other games, the rendering of entities is optimized as: close to the entity action animation frame rate is high, far away for the action animation frame rate limit, but in the MC, after testing, there is no renderer, or rendering optimization mod to do this, hope to optimize, the problem is most obvious in the server, or brush monster towers and other scenes

**Comment by tr7zw** [comment]
For Minecraft this doesn't make much sense. Calculating the animations takes nearly no time, and just rendering is slow. Additionally, you can't use LODs at far distances since Minecraft models are already at a bare minimum.

**Comment by 189521394** [comment]
> 对于Minecraft来说，这没有多大意义。计算动画几乎不需要时间，只是渲染很慢。此外，您不能在远距离使用 LOD，因为 Minecraft 模型已经处于最低限度。

Thank you for your interest!
I measured in the hypixel server, when the perspective is turned to a certain angle, or when looking at many entities in a mini-game, the frame rate will quickly drop to about 40, and I can basically determine that the problem is caused by a large number of entities

**Comment by tr7zw** [comment]
Yea it is, but this mod only disables rendering for entities you can't see. If you see them, then this mod does nothing for performance.
