### ISSUE TITLE
Instant crash in 1.19.3

### ISSUE THREAD

**Issue by ghost** [tr7zw/EntityCulling#98]
### Complete mod list:
- Entity culling 1.5.2
- Fabric API 73.2
- Fabric loader 0.14.14
- Lazy DFU 0.1.3

Crash report
[crash-2023-02-06_10.26.51-client.txt](https://github.com/tr7zw/EntityCulling/files/10667509/crash-2023-02-06_10.26.51-client.txt)

**Comment by tr7zw** [comment]
Use the 1.19.3 version, not 1.19.
